//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_CapaAccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_CRPCGEntities : DbContext
    {
        public BD_CRPCGEntities()
            : base("name=BD_CRPCGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int PRCGA_ELIMINA_BENEFICIO_PS(string cNroSol)
        {
            var cNroSolParameter = cNroSol != null ?
                new ObjectParameter("cNroSol", cNroSol) :
                new ObjectParameter("cNroSol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRCGA_ELIMINA_BENEFICIO_PS", cNroSolParameter);
        }
    
        public virtual int PRGUR_ELIMINA_ARCHIVOS(Nullable<int> i_idArchivo)
        {
            var i_idArchivoParameter = i_idArchivo.HasValue ?
                new ObjectParameter("I_idArchivo", i_idArchivo) :
                new ObjectParameter("I_idArchivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRGUR_ELIMINA_ARCHIVOS", i_idArchivoParameter);
        }
    
        public virtual ObjectResult<PRGUR_EliminaProcedimientos_PS_Result> PRGUR_EliminaProcedimientos_PS(string i_NroSolicitud, string i_CodProcedimiento)
        {
            var i_NroSolicitudParameter = i_NroSolicitud != null ?
                new ObjectParameter("I_NroSolicitud", i_NroSolicitud) :
                new ObjectParameter("I_NroSolicitud", typeof(string));
    
            var i_CodProcedimientoParameter = i_CodProcedimiento != null ?
                new ObjectParameter("I_CodProcedimiento", i_CodProcedimiento) :
                new ObjectParameter("I_CodProcedimiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRGUR_EliminaProcedimientos_PS_Result>("PRGUR_EliminaProcedimientos_PS", i_NroSolicitudParameter, i_CodProcedimientoParameter);
        }
    
        public virtual int PRGUR_Eliminar_OIQUIRURGICA(Nullable<int> i_idOrdenQx, string i_NroOrden, string i_Usuario, string i_Equipo)
        {
            var i_idOrdenQxParameter = i_idOrdenQx.HasValue ?
                new ObjectParameter("I_idOrdenQx", i_idOrdenQx) :
                new ObjectParameter("I_idOrdenQx", typeof(int));
    
            var i_NroOrdenParameter = i_NroOrden != null ?
                new ObjectParameter("I_NroOrden", i_NroOrden) :
                new ObjectParameter("I_NroOrden", typeof(string));
    
            var i_UsuarioParameter = i_Usuario != null ?
                new ObjectParameter("I_Usuario", i_Usuario) :
                new ObjectParameter("I_Usuario", typeof(string));
    
            var i_EquipoParameter = i_Equipo != null ?
                new ObjectParameter("I_Equipo", i_Equipo) :
                new ObjectParameter("I_Equipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRGUR_Eliminar_OIQUIRURGICA", i_idOrdenQxParameter, i_NroOrdenParameter, i_UsuarioParameter, i_EquipoParameter);
        }
    
        public virtual int PRGUR_EliminarCDESOIQx(Nullable<int> i_IdCorrelativoInterno, string i_Codigo, string tipoIns)
        {
            var i_IdCorrelativoInternoParameter = i_IdCorrelativoInterno.HasValue ?
                new ObjectParameter("I_IdCorrelativoInterno", i_IdCorrelativoInterno) :
                new ObjectParameter("I_IdCorrelativoInterno", typeof(int));
    
            var i_CodigoParameter = i_Codigo != null ?
                new ObjectParameter("I_Codigo", i_Codigo) :
                new ObjectParameter("I_Codigo", typeof(string));
    
            var tipoInsParameter = tipoIns != null ?
                new ObjectParameter("TipoIns", tipoIns) :
                new ObjectParameter("TipoIns", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRGUR_EliminarCDESOIQx", i_IdCorrelativoInternoParameter, i_CodigoParameter, tipoInsParameter);
        }
    
        public virtual int PRGUR_FAT_EliminarDetalles_Receta(Nullable<int> i_IdCorrelativoInterno, string tipoIns, string codigo)
        {
            var i_IdCorrelativoInternoParameter = i_IdCorrelativoInterno.HasValue ?
                new ObjectParameter("I_IdCorrelativoInterno", i_IdCorrelativoInterno) :
                new ObjectParameter("I_IdCorrelativoInterno", typeof(int));
    
            var tipoInsParameter = tipoIns != null ?
                new ObjectParameter("TipoIns", tipoIns) :
                new ObjectParameter("TipoIns", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRGUR_FAT_EliminarDetalles_Receta", i_IdCorrelativoInternoParameter, tipoInsParameter, codigoParameter);
        }
    
        public virtual ObjectResult<Filtros_Result> PRGUR_Filtros(string i_STipo)
        {
            var i_STipoParameter = i_STipo != null ?
                new ObjectParameter("I_STipo", i_STipo) :
                new ObjectParameter("I_STipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Filtros_Result>("PRGUR_Filtros", i_STipoParameter);
        }
    
        public virtual ObjectResult<SelectAutocomplete_Result> PRGUR_FiltrosAutocompletar(string i_STipo, string i_term)
        {
            var i_STipoParameter = i_STipo != null ?
                new ObjectParameter("I_STipo", i_STipo) :
                new ObjectParameter("I_STipo", typeof(string));
    
            var i_termParameter = i_term != null ?
                new ObjectParameter("I_term", i_term) :
                new ObjectParameter("I_term", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAutocomplete_Result>("PRGUR_FiltrosAutocompletar", i_STipoParameter, i_termParameter);
        }
    
        public virtual ObjectResult<ArchivosXCodCarta_Result> PRGUR_getArchivosXCarta(Nullable<int> i_CorrelativoInterno, string i_CodSolicitud)
        {
            var i_CorrelativoInternoParameter = i_CorrelativoInterno.HasValue ?
                new ObjectParameter("I_CorrelativoInterno", i_CorrelativoInterno) :
                new ObjectParameter("I_CorrelativoInterno", typeof(int));
    
            var i_CodSolicitudParameter = i_CodSolicitud != null ?
                new ObjectParameter("I_CodSolicitud", i_CodSolicitud) :
                new ObjectParameter("I_CodSolicitud", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ArchivosXCodCarta_Result>("PRGUR_getArchivosXCarta", i_CorrelativoInternoParameter, i_CodSolicitudParameter);
        }
    
        public virtual ObjectResult<BeneficiosProdecimientos_Result> PRGUR_getBenefYProcedxSolicitud(string i_NroSolicitud)
        {
            var i_NroSolicitudParameter = i_NroSolicitud != null ?
                new ObjectParameter("I_NroSolicitud", i_NroSolicitud) :
                new ObjectParameter("I_NroSolicitud", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BeneficiosProdecimientos_Result>("PRGUR_getBenefYProcedxSolicitud", i_NroSolicitudParameter);
        }
    
        public virtual ObjectResult<CartaGarantia_Result> PRGUR_getCarta(Nullable<int> i_codSolicitud)
        {
            var i_codSolicitudParameter = i_codSolicitud.HasValue ?
                new ObjectParameter("I_codSolicitud", i_codSolicitud) :
                new ObjectParameter("I_codSolicitud", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CartaGarantia_Result>("PRGUR_getCarta", i_codSolicitudParameter);
        }
    
        public virtual ObjectResult<CartaOIQx_Result> PRGUR_getCartaOIQx(Nullable<int> i_idOrden)
        {
            var i_idOrdenParameter = i_idOrden.HasValue ?
                new ObjectParameter("I_idOrden", i_idOrden) :
                new ObjectParameter("I_idOrden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CartaOIQx_Result>("PRGUR_getCartaOIQx", i_idOrdenParameter);
        }
    
        public virtual ObjectResult<CartaGarantiaPS_Result> PRGUR_getCartaPS(Nullable<int> i_NroSolicitud, string i_Departamento)
        {
            var i_NroSolicitudParameter = i_NroSolicitud.HasValue ?
                new ObjectParameter("I_NroSolicitud", i_NroSolicitud) :
                new ObjectParameter("I_NroSolicitud", typeof(int));
    
            var i_DepartamentoParameter = i_Departamento != null ?
                new ObjectParameter("I_Departamento", i_Departamento) :
                new ObjectParameter("I_Departamento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CartaGarantiaPS_Result>("PRGUR_getCartaPS", i_NroSolicitudParameter, i_DepartamentoParameter);
        }
    
        public virtual ObjectResult<CDESxOIQx_Result> PRGUR_getCDESxOIQuirurgica(Nullable<int> i_NroOIQx, string tipoIns)
        {
            var i_NroOIQxParameter = i_NroOIQx.HasValue ?
                new ObjectParameter("I_NroOIQx", i_NroOIQx) :
                new ObjectParameter("I_NroOIQx", typeof(int));
    
            var tipoInsParameter = tipoIns != null ?
                new ObjectParameter("TipoIns", tipoIns) :
                new ObjectParameter("TipoIns", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CDESxOIQx_Result>("PRGUR_getCDESxOIQuirurgica", i_NroOIQxParameter, tipoInsParameter);
        }
    
        public virtual ObjectResult<DxLabRx_Result> PRGUR_GetFAT_DxLAbRx(Nullable<int> i_idAtencion, string i_TipoIns)
        {
            var i_idAtencionParameter = i_idAtencion.HasValue ?
                new ObjectParameter("I_idAtencion", i_idAtencion) :
                new ObjectParameter("I_idAtencion", typeof(int));
    
            var i_TipoInsParameter = i_TipoIns != null ?
                new ObjectParameter("I_TipoIns", i_TipoIns) :
                new ObjectParameter("I_TipoIns", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DxLabRx_Result>("PRGUR_GetFAT_DxLAbRx", i_idAtencionParameter, i_TipoInsParameter);
        }
    
        public virtual ObjectResult<FATMedicamentos_Result> PRGUR_GetFAT_Medicamentos(Nullable<int> i_idAtencion)
        {
            var i_idAtencionParameter = i_idAtencion.HasValue ?
                new ObjectParameter("I_idAtencion", i_idAtencion) :
                new ObjectParameter("I_idAtencion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FATMedicamentos_Result>("PRGUR_GetFAT_Medicamentos", i_idAtencionParameter);
        }
    
        public virtual ObjectResult<OIQirurgica_Result> PRGUR_getOIQx(Nullable<int> i_idOrden)
        {
            var i_idOrdenParameter = i_idOrden.HasValue ?
                new ObjectParameter("I_idOrden", i_idOrden) :
                new ObjectParameter("I_idOrden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OIQirurgica_Result>("PRGUR_getOIQx", i_idOrdenParameter);
        }
    
        public virtual ObjectResult<PreQuirurgicoxCartaOiqx_Result> PRGUR_getPreQuirurgicoxCartaOiqx(Nullable<int> i_idSolicitud)
        {
            var i_idSolicitudParameter = i_idSolicitud.HasValue ?
                new ObjectParameter("I_idSolicitud", i_idSolicitud) :
                new ObjectParameter("I_idSolicitud", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PreQuirurgicoxCartaOiqx_Result>("PRGUR_getPreQuirurgicoxCartaOiqx", i_idSolicitudParameter);
        }
    
        public virtual ObjectResult<SuministrosxOIQuirurgica_Result> PRGUR_getSuministrosxOIQuirurgica(Nullable<int> i_NroOIQx)
        {
            var i_NroOIQxParameter = i_NroOIQx.HasValue ?
                new ObjectParameter("I_NroOIQx", i_NroOIQx) :
                new ObjectParameter("I_NroOIQx", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SuministrosxOIQuirurgica_Result>("PRGUR_getSuministrosxOIQuirurgica", i_NroOIQxParameter);
        }
    
        public virtual int PRGUR_Guarda_ArchivoFAT(Nullable<int> i_IdFAT, string i_OAA, string i_Tipo, byte[] i_Archivo, string i_User)
        {
            var i_IdFATParameter = i_IdFAT.HasValue ?
                new ObjectParameter("I_IdFAT", i_IdFAT) :
                new ObjectParameter("I_IdFAT", typeof(int));
    
            var i_OAAParameter = i_OAA != null ?
                new ObjectParameter("I_OAA", i_OAA) :
                new ObjectParameter("I_OAA", typeof(string));
    
            var i_TipoParameter = i_Tipo != null ?
                new ObjectParameter("I_Tipo", i_Tipo) :
                new ObjectParameter("I_Tipo", typeof(string));
    
            var i_ArchivoParameter = i_Archivo != null ?
                new ObjectParameter("I_Archivo", i_Archivo) :
                new ObjectParameter("I_Archivo", typeof(byte[]));
    
            var i_UserParameter = i_User != null ?
                new ObjectParameter("I_User", i_User) :
                new ObjectParameter("I_User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRGUR_Guarda_ArchivoFAT", i_IdFATParameter, i_OAAParameter, i_TipoParameter, i_ArchivoParameter, i_UserParameter);
        }
    
        public virtual int PRGUR_GUARDA_ARCHIVOS(Nullable<int> id_carta, string id_Solcarta, string iS_nomarchivo, string is_ctipo, string is_vp_usuario, string is_vp_equipo, byte[] is_archivo, string is_Origen)
        {
            var id_cartaParameter = id_carta.HasValue ?
                new ObjectParameter("id_carta", id_carta) :
                new ObjectParameter("id_carta", typeof(int));
    
            var id_SolcartaParameter = id_Solcarta != null ?
                new ObjectParameter("Id_Solcarta", id_Solcarta) :
                new ObjectParameter("Id_Solcarta", typeof(string));
    
            var iS_nomarchivoParameter = iS_nomarchivo != null ?
                new ObjectParameter("iS_nomarchivo", iS_nomarchivo) :
                new ObjectParameter("iS_nomarchivo", typeof(string));
    
            var is_ctipoParameter = is_ctipo != null ?
                new ObjectParameter("Is_ctipo", is_ctipo) :
                new ObjectParameter("Is_ctipo", typeof(string));
    
            var is_vp_usuarioParameter = is_vp_usuario != null ?
                new ObjectParameter("is_vp_usuario", is_vp_usuario) :
                new ObjectParameter("is_vp_usuario", typeof(string));
    
            var is_vp_equipoParameter = is_vp_equipo != null ?
                new ObjectParameter("is_vp_equipo", is_vp_equipo) :
                new ObjectParameter("is_vp_equipo", typeof(string));
    
            var is_archivoParameter = is_archivo != null ?
                new ObjectParameter("is_archivo", is_archivo) :
                new ObjectParameter("is_archivo", typeof(byte[]));
    
            var is_OrigenParameter = is_Origen != null ?
                new ObjectParameter("is_Origen", is_Origen) :
                new ObjectParameter("is_Origen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRGUR_GUARDA_ARCHIVOS", id_cartaParameter, id_SolcartaParameter, iS_nomarchivoParameter, is_ctipoParameter, is_vp_usuarioParameter, is_vp_equipoParameter, is_archivoParameter, is_OrigenParameter);
        }
    
        public virtual int PRGUR_GUARDA_CartaOrdenIQx(Nullable<int> id_carta, string id_Solcarta, string iS_estadoPreqx, string is_criteriopreqx, string is_observaciones, string is_fechaCirugia, Nullable<bool> is_qxProgramada, string is_sala, string is_tipo, string is_tipoAnestesia, string is_vp_usuario, string is_vp_equipo)
        {
            var id_cartaParameter = id_carta.HasValue ?
                new ObjectParameter("id_carta", id_carta) :
                new ObjectParameter("id_carta", typeof(int));
    
            var id_SolcartaParameter = id_Solcarta != null ?
                new ObjectParameter("Id_Solcarta", id_Solcarta) :
                new ObjectParameter("Id_Solcarta", typeof(string));
    
            var iS_estadoPreqxParameter = iS_estadoPreqx != null ?
                new ObjectParameter("iS_estadoPreqx", iS_estadoPreqx) :
                new ObjectParameter("iS_estadoPreqx", typeof(string));
    
            var is_criteriopreqxParameter = is_criteriopreqx != null ?
                new ObjectParameter("Is_criteriopreqx", is_criteriopreqx) :
                new ObjectParameter("Is_criteriopreqx", typeof(string));
    
            var is_observacionesParameter = is_observaciones != null ?
                new ObjectParameter("is_observaciones", is_observaciones) :
                new ObjectParameter("is_observaciones", typeof(string));
    
            var is_fechaCirugiaParameter = is_fechaCirugia != null ?
                new ObjectParameter("Is_fechaCirugia", is_fechaCirugia) :
                new ObjectParameter("Is_fechaCirugia", typeof(string));
    
            var is_qxProgramadaParameter = is_qxProgramada.HasValue ?
                new ObjectParameter("Is_qxProgramada", is_qxProgramada) :
                new ObjectParameter("Is_qxProgramada", typeof(bool));
    
            var is_salaParameter = is_sala != null ?
                new ObjectParameter("Is_sala", is_sala) :
                new ObjectParameter("Is_sala", typeof(string));
    
            var is_tipoParameter = is_tipo != null ?
                new ObjectParameter("is_tipo", is_tipo) :
                new ObjectParameter("is_tipo", typeof(string));
    
            var is_tipoAnestesiaParameter = is_tipoAnestesia != null ?
                new ObjectParameter("is_tipoAnestesia", is_tipoAnestesia) :
                new ObjectParameter("is_tipoAnestesia", typeof(string));
    
            var is_vp_usuarioParameter = is_vp_usuario != null ?
                new ObjectParameter("is_vp_usuario", is_vp_usuario) :
                new ObjectParameter("is_vp_usuario", typeof(string));
    
            var is_vp_equipoParameter = is_vp_equipo != null ?
                new ObjectParameter("is_vp_equipo", is_vp_equipo) :
                new ObjectParameter("is_vp_equipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRGUR_GUARDA_CartaOrdenIQx", id_cartaParameter, id_SolcartaParameter, iS_estadoPreqxParameter, is_criteriopreqxParameter, is_observacionesParameter, is_fechaCirugiaParameter, is_qxProgramadaParameter, is_salaParameter, is_tipoParameter, is_tipoAnestesiaParameter, is_vp_usuarioParameter, is_vp_equipoParameter);
        }
    
        public virtual ObjectResult<CARTASERVICIO_Result> PRGUR_GUARDAR_CARTASERVICIO(string i_idSol_CarGarantia, string i_Usuario, string i_Equipo, string i_Num_Doc_Paciente, string i_HC_paciente, string i_Num_Telefono, string i_Nom_Paciente, string i_Fnacimiento, string i_Num_Celular, string i_CodigoAfiliado, Nullable<int> i_Edad, string i_CorreoContacto, string i_idFinanciador, string i_Contratante, string i_idEspecialidad, string i_ImporteCarta, string i_PSdiagnostico, string i_PSMed_Tratante, string i_PSTiempo_year, string i_PSTiempo_Mes, string i_PSTiempo_dia, string i_PSObs_medTratante, string i_PSTipoAtencion, Nullable<int> i_PSDiashospitalizado, string i_PSTitular, string i_PSParentesco, string i_PSnumContrato, string i_PSEstadoContrato, string i_PSPlan, string i_PSProducto, Nullable<System.DateTime> i_Fcontrato, Nullable<System.DateTime> i_FAfiliacion, Nullable<System.DateTime> i_Finivigencia, byte[] i_Anexo, string i_tipodocto)
        {
            var i_idSol_CarGarantiaParameter = i_idSol_CarGarantia != null ?
                new ObjectParameter("I_idSol_CarGarantia", i_idSol_CarGarantia) :
                new ObjectParameter("I_idSol_CarGarantia", typeof(string));
    
            var i_UsuarioParameter = i_Usuario != null ?
                new ObjectParameter("I_Usuario", i_Usuario) :
                new ObjectParameter("I_Usuario", typeof(string));
    
            var i_EquipoParameter = i_Equipo != null ?
                new ObjectParameter("I_Equipo", i_Equipo) :
                new ObjectParameter("I_Equipo", typeof(string));
    
            var i_Num_Doc_PacienteParameter = i_Num_Doc_Paciente != null ?
                new ObjectParameter("I_Num_Doc_Paciente", i_Num_Doc_Paciente) :
                new ObjectParameter("I_Num_Doc_Paciente", typeof(string));
    
            var i_HC_pacienteParameter = i_HC_paciente != null ?
                new ObjectParameter("I_HC_paciente", i_HC_paciente) :
                new ObjectParameter("I_HC_paciente", typeof(string));
    
            var i_Num_TelefonoParameter = i_Num_Telefono != null ?
                new ObjectParameter("I_Num_Telefono", i_Num_Telefono) :
                new ObjectParameter("I_Num_Telefono", typeof(string));
    
            var i_Nom_PacienteParameter = i_Nom_Paciente != null ?
                new ObjectParameter("I_Nom_Paciente", i_Nom_Paciente) :
                new ObjectParameter("I_Nom_Paciente", typeof(string));
    
            var i_FnacimientoParameter = i_Fnacimiento != null ?
                new ObjectParameter("I_Fnacimiento", i_Fnacimiento) :
                new ObjectParameter("I_Fnacimiento", typeof(string));
    
            var i_Num_CelularParameter = i_Num_Celular != null ?
                new ObjectParameter("I_Num_Celular", i_Num_Celular) :
                new ObjectParameter("I_Num_Celular", typeof(string));
    
            var i_CodigoAfiliadoParameter = i_CodigoAfiliado != null ?
                new ObjectParameter("I_CodigoAfiliado", i_CodigoAfiliado) :
                new ObjectParameter("I_CodigoAfiliado", typeof(string));
    
            var i_EdadParameter = i_Edad.HasValue ?
                new ObjectParameter("I_Edad", i_Edad) :
                new ObjectParameter("I_Edad", typeof(int));
    
            var i_CorreoContactoParameter = i_CorreoContacto != null ?
                new ObjectParameter("I_CorreoContacto", i_CorreoContacto) :
                new ObjectParameter("I_CorreoContacto", typeof(string));
    
            var i_idFinanciadorParameter = i_idFinanciador != null ?
                new ObjectParameter("I_idFinanciador", i_idFinanciador) :
                new ObjectParameter("I_idFinanciador", typeof(string));
    
            var i_ContratanteParameter = i_Contratante != null ?
                new ObjectParameter("I_Contratante", i_Contratante) :
                new ObjectParameter("I_Contratante", typeof(string));
    
            var i_idEspecialidadParameter = i_idEspecialidad != null ?
                new ObjectParameter("I_idEspecialidad", i_idEspecialidad) :
                new ObjectParameter("I_idEspecialidad", typeof(string));
    
            var i_ImporteCartaParameter = i_ImporteCarta != null ?
                new ObjectParameter("I_ImporteCarta", i_ImporteCarta) :
                new ObjectParameter("I_ImporteCarta", typeof(string));
    
            var i_PSdiagnosticoParameter = i_PSdiagnostico != null ?
                new ObjectParameter("I_PSdiagnostico", i_PSdiagnostico) :
                new ObjectParameter("I_PSdiagnostico", typeof(string));
    
            var i_PSMed_TratanteParameter = i_PSMed_Tratante != null ?
                new ObjectParameter("I_PSMed_Tratante", i_PSMed_Tratante) :
                new ObjectParameter("I_PSMed_Tratante", typeof(string));
    
            var i_PSTiempo_yearParameter = i_PSTiempo_year != null ?
                new ObjectParameter("I_PSTiempo_year", i_PSTiempo_year) :
                new ObjectParameter("I_PSTiempo_year", typeof(string));
    
            var i_PSTiempo_MesParameter = i_PSTiempo_Mes != null ?
                new ObjectParameter("I_PSTiempo_Mes", i_PSTiempo_Mes) :
                new ObjectParameter("I_PSTiempo_Mes", typeof(string));
    
            var i_PSTiempo_diaParameter = i_PSTiempo_dia != null ?
                new ObjectParameter("I_PSTiempo_dia", i_PSTiempo_dia) :
                new ObjectParameter("I_PSTiempo_dia", typeof(string));
    
            var i_PSObs_medTratanteParameter = i_PSObs_medTratante != null ?
                new ObjectParameter("I_PSObs_medTratante", i_PSObs_medTratante) :
                new ObjectParameter("I_PSObs_medTratante", typeof(string));
    
            var i_PSTipoAtencionParameter = i_PSTipoAtencion != null ?
                new ObjectParameter("I_PSTipoAtencion", i_PSTipoAtencion) :
                new ObjectParameter("I_PSTipoAtencion", typeof(string));
    
            var i_PSDiashospitalizadoParameter = i_PSDiashospitalizado.HasValue ?
                new ObjectParameter("I_PSDiashospitalizado", i_PSDiashospitalizado) :
                new ObjectParameter("I_PSDiashospitalizado", typeof(int));
    
            var i_PSTitularParameter = i_PSTitular != null ?
                new ObjectParameter("I_PSTitular", i_PSTitular) :
                new ObjectParameter("I_PSTitular", typeof(string));
    
            var i_PSParentescoParameter = i_PSParentesco != null ?
                new ObjectParameter("I_PSParentesco", i_PSParentesco) :
                new ObjectParameter("I_PSParentesco", typeof(string));
    
            var i_PSnumContratoParameter = i_PSnumContrato != null ?
                new ObjectParameter("I_PSnumContrato", i_PSnumContrato) :
                new ObjectParameter("I_PSnumContrato", typeof(string));
    
            var i_PSEstadoContratoParameter = i_PSEstadoContrato != null ?
                new ObjectParameter("I_PSEstadoContrato", i_PSEstadoContrato) :
                new ObjectParameter("I_PSEstadoContrato", typeof(string));
    
            var i_PSPlanParameter = i_PSPlan != null ?
                new ObjectParameter("I_PSPlan", i_PSPlan) :
                new ObjectParameter("I_PSPlan", typeof(string));
    
            var i_PSProductoParameter = i_PSProducto != null ?
                new ObjectParameter("I_PSProducto", i_PSProducto) :
                new ObjectParameter("I_PSProducto", typeof(string));
    
            var i_FcontratoParameter = i_Fcontrato.HasValue ?
                new ObjectParameter("I_Fcontrato", i_Fcontrato) :
                new ObjectParameter("I_Fcontrato", typeof(System.DateTime));
    
            var i_FAfiliacionParameter = i_FAfiliacion.HasValue ?
                new ObjectParameter("I_FAfiliacion", i_FAfiliacion) :
                new ObjectParameter("I_FAfiliacion", typeof(System.DateTime));
    
            var i_FinivigenciaParameter = i_Finivigencia.HasValue ?
                new ObjectParameter("I_Finivigencia", i_Finivigencia) :
                new ObjectParameter("I_Finivigencia", typeof(System.DateTime));
    
            var i_AnexoParameter = i_Anexo != null ?
                new ObjectParameter("I_Anexo", i_Anexo) :
                new ObjectParameter("I_Anexo", typeof(byte[]));
    
            var i_tipodoctoParameter = i_tipodocto != null ?
                new ObjectParameter("I_tipodocto", i_tipodocto) :
                new ObjectParameter("I_tipodocto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CARTASERVICIO_Result>("PRGUR_GUARDAR_CARTASERVICIO", i_idSol_CarGarantiaParameter, i_UsuarioParameter, i_EquipoParameter, i_Num_Doc_PacienteParameter, i_HC_pacienteParameter, i_Num_TelefonoParameter, i_Nom_PacienteParameter, i_FnacimientoParameter, i_Num_CelularParameter, i_CodigoAfiliadoParameter, i_EdadParameter, i_CorreoContactoParameter, i_idFinanciadorParameter, i_ContratanteParameter, i_idEspecialidadParameter, i_ImporteCartaParameter, i_PSdiagnosticoParameter, i_PSMed_TratanteParameter, i_PSTiempo_yearParameter, i_PSTiempo_MesParameter, i_PSTiempo_diaParameter, i_PSObs_medTratanteParameter, i_PSTipoAtencionParameter, i_PSDiashospitalizadoParameter, i_PSTitularParameter, i_PSParentescoParameter, i_PSnumContratoParameter, i_PSEstadoContratoParameter, i_PSPlanParameter, i_PSProductoParameter, i_FcontratoParameter, i_FAfiliacionParameter, i_FinivigenciaParameter, i_AnexoParameter, i_tipodoctoParameter);
        }
    
        public virtual ObjectResult<CodIdOIQx_Result> PRGUR_GUARDAR_OIQUIRURGICA(Nullable<int> i_idOrdenQx, string i_NroOrden, string i_Usuario, string i_Equipo, string i_Num_Doc_Paciente, string i_HC_paciente, string i_Edad, string i_Num_Celular, string i_Nom_Paciente, string i_CorreoContacto, string i_codFinanciador, string i_codEspecialidad, string i_codTipoCirugia, string i_Tiempo_year, string i_Tiempo_Mes, string i_Tiempo_dia, string i_HorasQx, string i_Alergias, string i_Morbilidades, Nullable<bool> i_Requisito1, Nullable<bool> i_Requisito2, Nullable<bool> i_Requisito3, Nullable<bool> i_Requisito4, Nullable<bool> i_Requisito5, Nullable<bool> i_Requisito6, Nullable<bool> i_Requisito7, string i_Requisito8, string i_FCirugia, string i_HoraCirugia, string i_FHospitalizacion, string i_HoraHosp, string i_Testancia, Nullable<bool> i_Profilaxis, string i_Justificacion, string i_CMPmedicoReg, Nullable<bool> i_ValidaTiempo, string i_TipoAnestesia)
        {
            var i_idOrdenQxParameter = i_idOrdenQx.HasValue ?
                new ObjectParameter("I_idOrdenQx", i_idOrdenQx) :
                new ObjectParameter("I_idOrdenQx", typeof(int));
    
            var i_NroOrdenParameter = i_NroOrden != null ?
                new ObjectParameter("I_NroOrden", i_NroOrden) :
                new ObjectParameter("I_NroOrden", typeof(string));
    
            var i_UsuarioParameter = i_Usuario != null ?
                new ObjectParameter("I_Usuario", i_Usuario) :
                new ObjectParameter("I_Usuario", typeof(string));
    
            var i_EquipoParameter = i_Equipo != null ?
                new ObjectParameter("I_Equipo", i_Equipo) :
                new ObjectParameter("I_Equipo", typeof(string));
    
            var i_Num_Doc_PacienteParameter = i_Num_Doc_Paciente != null ?
                new ObjectParameter("I_Num_Doc_Paciente", i_Num_Doc_Paciente) :
                new ObjectParameter("I_Num_Doc_Paciente", typeof(string));
    
            var i_HC_pacienteParameter = i_HC_paciente != null ?
                new ObjectParameter("I_HC_paciente", i_HC_paciente) :
                new ObjectParameter("I_HC_paciente", typeof(string));
    
            var i_EdadParameter = i_Edad != null ?
                new ObjectParameter("I_Edad", i_Edad) :
                new ObjectParameter("I_Edad", typeof(string));
    
            var i_Num_CelularParameter = i_Num_Celular != null ?
                new ObjectParameter("I_Num_Celular", i_Num_Celular) :
                new ObjectParameter("I_Num_Celular", typeof(string));
    
            var i_Nom_PacienteParameter = i_Nom_Paciente != null ?
                new ObjectParameter("I_Nom_Paciente", i_Nom_Paciente) :
                new ObjectParameter("I_Nom_Paciente", typeof(string));
    
            var i_CorreoContactoParameter = i_CorreoContacto != null ?
                new ObjectParameter("I_CorreoContacto", i_CorreoContacto) :
                new ObjectParameter("I_CorreoContacto", typeof(string));
    
            var i_codFinanciadorParameter = i_codFinanciador != null ?
                new ObjectParameter("I_codFinanciador", i_codFinanciador) :
                new ObjectParameter("I_codFinanciador", typeof(string));
    
            var i_codEspecialidadParameter = i_codEspecialidad != null ?
                new ObjectParameter("I_codEspecialidad", i_codEspecialidad) :
                new ObjectParameter("I_codEspecialidad", typeof(string));
    
            var i_codTipoCirugiaParameter = i_codTipoCirugia != null ?
                new ObjectParameter("I_codTipoCirugia", i_codTipoCirugia) :
                new ObjectParameter("I_codTipoCirugia", typeof(string));
    
            var i_Tiempo_yearParameter = i_Tiempo_year != null ?
                new ObjectParameter("I_Tiempo_year", i_Tiempo_year) :
                new ObjectParameter("I_Tiempo_year", typeof(string));
    
            var i_Tiempo_MesParameter = i_Tiempo_Mes != null ?
                new ObjectParameter("I_Tiempo_Mes", i_Tiempo_Mes) :
                new ObjectParameter("I_Tiempo_Mes", typeof(string));
    
            var i_Tiempo_diaParameter = i_Tiempo_dia != null ?
                new ObjectParameter("I_Tiempo_dia", i_Tiempo_dia) :
                new ObjectParameter("I_Tiempo_dia", typeof(string));
    
            var i_HorasQxParameter = i_HorasQx != null ?
                new ObjectParameter("I_HorasQx", i_HorasQx) :
                new ObjectParameter("I_HorasQx", typeof(string));
    
            var i_AlergiasParameter = i_Alergias != null ?
                new ObjectParameter("I_Alergias", i_Alergias) :
                new ObjectParameter("I_Alergias", typeof(string));
    
            var i_MorbilidadesParameter = i_Morbilidades != null ?
                new ObjectParameter("I_Morbilidades", i_Morbilidades) :
                new ObjectParameter("I_Morbilidades", typeof(string));
    
            var i_Requisito1Parameter = i_Requisito1.HasValue ?
                new ObjectParameter("I_Requisito1", i_Requisito1) :
                new ObjectParameter("I_Requisito1", typeof(bool));
    
            var i_Requisito2Parameter = i_Requisito2.HasValue ?
                new ObjectParameter("I_Requisito2", i_Requisito2) :
                new ObjectParameter("I_Requisito2", typeof(bool));
    
            var i_Requisito3Parameter = i_Requisito3.HasValue ?
                new ObjectParameter("I_Requisito3", i_Requisito3) :
                new ObjectParameter("I_Requisito3", typeof(bool));
    
            var i_Requisito4Parameter = i_Requisito4.HasValue ?
                new ObjectParameter("I_Requisito4", i_Requisito4) :
                new ObjectParameter("I_Requisito4", typeof(bool));
    
            var i_Requisito5Parameter = i_Requisito5.HasValue ?
                new ObjectParameter("I_Requisito5", i_Requisito5) :
                new ObjectParameter("I_Requisito5", typeof(bool));
    
            var i_Requisito6Parameter = i_Requisito6.HasValue ?
                new ObjectParameter("I_Requisito6", i_Requisito6) :
                new ObjectParameter("I_Requisito6", typeof(bool));
    
            var i_Requisito7Parameter = i_Requisito7.HasValue ?
                new ObjectParameter("I_Requisito7", i_Requisito7) :
                new ObjectParameter("I_Requisito7", typeof(bool));
    
            var i_Requisito8Parameter = i_Requisito8 != null ?
                new ObjectParameter("I_Requisito8", i_Requisito8) :
                new ObjectParameter("I_Requisito8", typeof(string));
    
            var i_FCirugiaParameter = i_FCirugia != null ?
                new ObjectParameter("I_FCirugia", i_FCirugia) :
                new ObjectParameter("I_FCirugia", typeof(string));
    
            var i_HoraCirugiaParameter = i_HoraCirugia != null ?
                new ObjectParameter("I_HoraCirugia", i_HoraCirugia) :
                new ObjectParameter("I_HoraCirugia", typeof(string));
    
            var i_FHospitalizacionParameter = i_FHospitalizacion != null ?
                new ObjectParameter("I_FHospitalizacion", i_FHospitalizacion) :
                new ObjectParameter("I_FHospitalizacion", typeof(string));
    
            var i_HoraHospParameter = i_HoraHosp != null ?
                new ObjectParameter("I_HoraHosp", i_HoraHosp) :
                new ObjectParameter("I_HoraHosp", typeof(string));
    
            var i_TestanciaParameter = i_Testancia != null ?
                new ObjectParameter("I_Testancia", i_Testancia) :
                new ObjectParameter("I_Testancia", typeof(string));
    
            var i_ProfilaxisParameter = i_Profilaxis.HasValue ?
                new ObjectParameter("I_Profilaxis", i_Profilaxis) :
                new ObjectParameter("I_Profilaxis", typeof(bool));
    
            var i_JustificacionParameter = i_Justificacion != null ?
                new ObjectParameter("I_Justificacion", i_Justificacion) :
                new ObjectParameter("I_Justificacion", typeof(string));
    
            var i_CMPmedicoRegParameter = i_CMPmedicoReg != null ?
                new ObjectParameter("I_CMPmedicoReg", i_CMPmedicoReg) :
                new ObjectParameter("I_CMPmedicoReg", typeof(string));
    
            var i_ValidaTiempoParameter = i_ValidaTiempo.HasValue ?
                new ObjectParameter("I_ValidaTiempo", i_ValidaTiempo) :
                new ObjectParameter("I_ValidaTiempo", typeof(bool));
    
            var i_TipoAnestesiaParameter = i_TipoAnestesia != null ?
                new ObjectParameter("I_TipoAnestesia", i_TipoAnestesia) :
                new ObjectParameter("I_TipoAnestesia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CodIdOIQx_Result>("PRGUR_GUARDAR_OIQUIRURGICA", i_idOrdenQxParameter, i_NroOrdenParameter, i_UsuarioParameter, i_EquipoParameter, i_Num_Doc_PacienteParameter, i_HC_pacienteParameter, i_EdadParameter, i_Num_CelularParameter, i_Nom_PacienteParameter, i_CorreoContactoParameter, i_codFinanciadorParameter, i_codEspecialidadParameter, i_codTipoCirugiaParameter, i_Tiempo_yearParameter, i_Tiempo_MesParameter, i_Tiempo_diaParameter, i_HorasQxParameter, i_AlergiasParameter, i_MorbilidadesParameter, i_Requisito1Parameter, i_Requisito2Parameter, i_Requisito3Parameter, i_Requisito4Parameter, i_Requisito5Parameter, i_Requisito6Parameter, i_Requisito7Parameter, i_Requisito8Parameter, i_FCirugiaParameter, i_HoraCirugiaParameter, i_FHospitalizacionParameter, i_HoraHospParameter, i_TestanciaParameter, i_ProfilaxisParameter, i_JustificacionParameter, i_CMPmedicoRegParameter, i_ValidaTiempoParameter, i_TipoAnestesiaParameter);
        }
    
        public virtual int PRGUR_GuardarBenefYProced_PS(string i_NroSolicitud, string i_Usuario, string i_Equipo, string i_Codigo, string i_Descripcion, Nullable<int> i_CorrelativoInt, string i_cpfijo, string i_cpVariable, Nullable<int> i_flagSeleccion, string i_tipo)
        {
            var i_NroSolicitudParameter = i_NroSolicitud != null ?
                new ObjectParameter("I_NroSolicitud", i_NroSolicitud) :
                new ObjectParameter("I_NroSolicitud", typeof(string));
    
            var i_UsuarioParameter = i_Usuario != null ?
                new ObjectParameter("I_Usuario", i_Usuario) :
                new ObjectParameter("I_Usuario", typeof(string));
    
            var i_EquipoParameter = i_Equipo != null ?
                new ObjectParameter("I_Equipo", i_Equipo) :
                new ObjectParameter("I_Equipo", typeof(string));
    
            var i_CodigoParameter = i_Codigo != null ?
                new ObjectParameter("I_Codigo", i_Codigo) :
                new ObjectParameter("I_Codigo", typeof(string));
    
            var i_DescripcionParameter = i_Descripcion != null ?
                new ObjectParameter("I_Descripcion", i_Descripcion) :
                new ObjectParameter("I_Descripcion", typeof(string));
    
            var i_CorrelativoIntParameter = i_CorrelativoInt.HasValue ?
                new ObjectParameter("I_CorrelativoInt", i_CorrelativoInt) :
                new ObjectParameter("I_CorrelativoInt", typeof(int));
    
            var i_cpfijoParameter = i_cpfijo != null ?
                new ObjectParameter("I_cpfijo", i_cpfijo) :
                new ObjectParameter("I_cpfijo", typeof(string));
    
            var i_cpVariableParameter = i_cpVariable != null ?
                new ObjectParameter("I_cpVariable", i_cpVariable) :
                new ObjectParameter("I_cpVariable", typeof(string));
    
            var i_flagSeleccionParameter = i_flagSeleccion.HasValue ?
                new ObjectParameter("I_flagSeleccion", i_flagSeleccion) :
                new ObjectParameter("I_flagSeleccion", typeof(int));
    
            var i_tipoParameter = i_tipo != null ?
                new ObjectParameter("I_tipo", i_tipo) :
                new ObjectParameter("I_tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRGUR_GuardarBenefYProced_PS", i_NroSolicitudParameter, i_UsuarioParameter, i_EquipoParameter, i_CodigoParameter, i_DescripcionParameter, i_CorrelativoIntParameter, i_cpfijoParameter, i_cpVariableParameter, i_flagSeleccionParameter, i_tipoParameter);
        }
    
        public virtual int PRGUR_guardarCDESxOIQuirurgica(Nullable<int> i_NroOIQx, string i_CodigoOIQx, string i_Codigo, string i_Usuario, string i_Equipo, string tipoIns)
        {
            var i_NroOIQxParameter = i_NroOIQx.HasValue ?
                new ObjectParameter("I_NroOIQx", i_NroOIQx) :
                new ObjectParameter("I_NroOIQx", typeof(int));
    
            var i_CodigoOIQxParameter = i_CodigoOIQx != null ?
                new ObjectParameter("I_CodigoOIQx", i_CodigoOIQx) :
                new ObjectParameter("I_CodigoOIQx", typeof(string));
    
            var i_CodigoParameter = i_Codigo != null ?
                new ObjectParameter("I_Codigo", i_Codigo) :
                new ObjectParameter("I_Codigo", typeof(string));
    
            var i_UsuarioParameter = i_Usuario != null ?
                new ObjectParameter("I_Usuario", i_Usuario) :
                new ObjectParameter("I_Usuario", typeof(string));
    
            var i_EquipoParameter = i_Equipo != null ?
                new ObjectParameter("I_Equipo", i_Equipo) :
                new ObjectParameter("I_Equipo", typeof(string));
    
            var tipoInsParameter = tipoIns != null ?
                new ObjectParameter("TipoIns", tipoIns) :
                new ObjectParameter("TipoIns", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRGUR_guardarCDESxOIQuirurgica", i_NroOIQxParameter, i_CodigoOIQxParameter, i_CodigoParameter, i_UsuarioParameter, i_EquipoParameter, tipoInsParameter);
        }
    
        public virtual ObjectResult<idNroFAT_Result> PRGUR_GuardarFAT(Nullable<int> i_idFAT, string i_NroAtencion, string i_Usuario, string i_Equipo, string i_Num_Doc_Paciente, string i_FecUltimaAtencion, string i_HC_paciente, string i_Edad, string i_Celular, string i_Telefono, string i_Email, string i_Sexo, Nullable<int> i_TipoAtencion, Nullable<int> i_Modalidad, string i_Nom_Paciente, string i_ApePaterno_Paciente, string i_ApeMaterno_Paciente, string i_codFinanciador, string i_Anamnesis, string i_Motivo, string i_Tratamiento, string i_Medicacion, string i_RNE, string i_CMP)
        {
            var i_idFATParameter = i_idFAT.HasValue ?
                new ObjectParameter("I_idFAT", i_idFAT) :
                new ObjectParameter("I_idFAT", typeof(int));
    
            var i_NroAtencionParameter = i_NroAtencion != null ?
                new ObjectParameter("I_NroAtencion", i_NroAtencion) :
                new ObjectParameter("I_NroAtencion", typeof(string));
    
            var i_UsuarioParameter = i_Usuario != null ?
                new ObjectParameter("I_Usuario", i_Usuario) :
                new ObjectParameter("I_Usuario", typeof(string));
    
            var i_EquipoParameter = i_Equipo != null ?
                new ObjectParameter("I_Equipo", i_Equipo) :
                new ObjectParameter("I_Equipo", typeof(string));
    
            var i_Num_Doc_PacienteParameter = i_Num_Doc_Paciente != null ?
                new ObjectParameter("I_Num_Doc_Paciente", i_Num_Doc_Paciente) :
                new ObjectParameter("I_Num_Doc_Paciente", typeof(string));
    
            var i_FecUltimaAtencionParameter = i_FecUltimaAtencion != null ?
                new ObjectParameter("I_FecUltimaAtencion", i_FecUltimaAtencion) :
                new ObjectParameter("I_FecUltimaAtencion", typeof(string));
    
            var i_HC_pacienteParameter = i_HC_paciente != null ?
                new ObjectParameter("I_HC_paciente", i_HC_paciente) :
                new ObjectParameter("I_HC_paciente", typeof(string));
    
            var i_EdadParameter = i_Edad != null ?
                new ObjectParameter("I_Edad", i_Edad) :
                new ObjectParameter("I_Edad", typeof(string));
    
            var i_CelularParameter = i_Celular != null ?
                new ObjectParameter("I_Celular", i_Celular) :
                new ObjectParameter("I_Celular", typeof(string));
    
            var i_TelefonoParameter = i_Telefono != null ?
                new ObjectParameter("I_Telefono", i_Telefono) :
                new ObjectParameter("I_Telefono", typeof(string));
    
            var i_EmailParameter = i_Email != null ?
                new ObjectParameter("I_Email", i_Email) :
                new ObjectParameter("I_Email", typeof(string));
    
            var i_SexoParameter = i_Sexo != null ?
                new ObjectParameter("I_Sexo", i_Sexo) :
                new ObjectParameter("I_Sexo", typeof(string));
    
            var i_TipoAtencionParameter = i_TipoAtencion.HasValue ?
                new ObjectParameter("I_TipoAtencion", i_TipoAtencion) :
                new ObjectParameter("I_TipoAtencion", typeof(int));
    
            var i_ModalidadParameter = i_Modalidad.HasValue ?
                new ObjectParameter("I_Modalidad", i_Modalidad) :
                new ObjectParameter("I_Modalidad", typeof(int));
    
            var i_Nom_PacienteParameter = i_Nom_Paciente != null ?
                new ObjectParameter("I_Nom_Paciente", i_Nom_Paciente) :
                new ObjectParameter("I_Nom_Paciente", typeof(string));
    
            var i_ApePaterno_PacienteParameter = i_ApePaterno_Paciente != null ?
                new ObjectParameter("I_ApePaterno_Paciente", i_ApePaterno_Paciente) :
                new ObjectParameter("I_ApePaterno_Paciente", typeof(string));
    
            var i_ApeMaterno_PacienteParameter = i_ApeMaterno_Paciente != null ?
                new ObjectParameter("I_ApeMaterno_Paciente", i_ApeMaterno_Paciente) :
                new ObjectParameter("I_ApeMaterno_Paciente", typeof(string));
    
            var i_codFinanciadorParameter = i_codFinanciador != null ?
                new ObjectParameter("I_codFinanciador", i_codFinanciador) :
                new ObjectParameter("I_codFinanciador", typeof(string));
    
            var i_AnamnesisParameter = i_Anamnesis != null ?
                new ObjectParameter("I_Anamnesis", i_Anamnesis) :
                new ObjectParameter("I_Anamnesis", typeof(string));
    
            var i_MotivoParameter = i_Motivo != null ?
                new ObjectParameter("I_Motivo", i_Motivo) :
                new ObjectParameter("I_Motivo", typeof(string));
    
            var i_TratamientoParameter = i_Tratamiento != null ?
                new ObjectParameter("I_Tratamiento", i_Tratamiento) :
                new ObjectParameter("I_Tratamiento", typeof(string));
    
            var i_MedicacionParameter = i_Medicacion != null ?
                new ObjectParameter("I_Medicacion", i_Medicacion) :
                new ObjectParameter("I_Medicacion", typeof(string));
    
            var i_RNEParameter = i_RNE != null ?
                new ObjectParameter("I_RNE", i_RNE) :
                new ObjectParameter("I_RNE", typeof(string));
    
            var i_CMPParameter = i_CMP != null ?
                new ObjectParameter("I_CMP", i_CMP) :
                new ObjectParameter("I_CMP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<idNroFAT_Result>("PRGUR_GuardarFAT", i_idFATParameter, i_NroAtencionParameter, i_UsuarioParameter, i_EquipoParameter, i_Num_Doc_PacienteParameter, i_FecUltimaAtencionParameter, i_HC_pacienteParameter, i_EdadParameter, i_CelularParameter, i_TelefonoParameter, i_EmailParameter, i_SexoParameter, i_TipoAtencionParameter, i_ModalidadParameter, i_Nom_PacienteParameter, i_ApePaterno_PacienteParameter, i_ApeMaterno_PacienteParameter, i_codFinanciadorParameter, i_AnamnesisParameter, i_MotivoParameter, i_TratamientoParameter, i_MedicacionParameter, i_RNEParameter, i_CMPParameter);
        }
    
        public virtual int PRGUR_GuardarFAT_DxLABRx(Nullable<int> i_idAtencion, string i_TipoIns, string i_TipoDX, string i_Codigo, string i_Observacion, string i_Usuario)
        {
            var i_idAtencionParameter = i_idAtencion.HasValue ?
                new ObjectParameter("I_idAtencion", i_idAtencion) :
                new ObjectParameter("I_idAtencion", typeof(int));
    
            var i_TipoInsParameter = i_TipoIns != null ?
                new ObjectParameter("I_TipoIns", i_TipoIns) :
                new ObjectParameter("I_TipoIns", typeof(string));
    
            var i_TipoDXParameter = i_TipoDX != null ?
                new ObjectParameter("I_TipoDX", i_TipoDX) :
                new ObjectParameter("I_TipoDX", typeof(string));
    
            var i_CodigoParameter = i_Codigo != null ?
                new ObjectParameter("I_Codigo", i_Codigo) :
                new ObjectParameter("I_Codigo", typeof(string));
    
            var i_ObservacionParameter = i_Observacion != null ?
                new ObjectParameter("I_Observacion", i_Observacion) :
                new ObjectParameter("I_Observacion", typeof(string));
    
            var i_UsuarioParameter = i_Usuario != null ?
                new ObjectParameter("I_Usuario", i_Usuario) :
                new ObjectParameter("I_Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRGUR_GuardarFAT_DxLABRx", i_idAtencionParameter, i_TipoInsParameter, i_TipoDXParameter, i_CodigoParameter, i_ObservacionParameter, i_UsuarioParameter);
        }
    
        public virtual int PRGUR_GuardarFAT_Medicamentos(Nullable<int> i_idAtencion, string i_Codigo, string i_Nombre, string i_DescripcionPA, string i_DOSIS, string i_Via, string i_Duracion, string i_intervalo, string i_Cantidad, string i_TipoIns, string i_Otros, string i_Usuario, string i_Forma)
        {
            var i_idAtencionParameter = i_idAtencion.HasValue ?
                new ObjectParameter("I_idAtencion", i_idAtencion) :
                new ObjectParameter("I_idAtencion", typeof(int));
    
            var i_CodigoParameter = i_Codigo != null ?
                new ObjectParameter("I_Codigo", i_Codigo) :
                new ObjectParameter("I_Codigo", typeof(string));
    
            var i_NombreParameter = i_Nombre != null ?
                new ObjectParameter("I_Nombre", i_Nombre) :
                new ObjectParameter("I_Nombre", typeof(string));
    
            var i_DescripcionPAParameter = i_DescripcionPA != null ?
                new ObjectParameter("I_DescripcionPA", i_DescripcionPA) :
                new ObjectParameter("I_DescripcionPA", typeof(string));
    
            var i_DOSISParameter = i_DOSIS != null ?
                new ObjectParameter("I_DOSIS", i_DOSIS) :
                new ObjectParameter("I_DOSIS", typeof(string));
    
            var i_ViaParameter = i_Via != null ?
                new ObjectParameter("I_Via", i_Via) :
                new ObjectParameter("I_Via", typeof(string));
    
            var i_DuracionParameter = i_Duracion != null ?
                new ObjectParameter("I_Duracion", i_Duracion) :
                new ObjectParameter("I_Duracion", typeof(string));
    
            var i_intervaloParameter = i_intervalo != null ?
                new ObjectParameter("I_intervalo", i_intervalo) :
                new ObjectParameter("I_intervalo", typeof(string));
    
            var i_CantidadParameter = i_Cantidad != null ?
                new ObjectParameter("I_Cantidad", i_Cantidad) :
                new ObjectParameter("I_Cantidad", typeof(string));
    
            var i_TipoInsParameter = i_TipoIns != null ?
                new ObjectParameter("I_TipoIns", i_TipoIns) :
                new ObjectParameter("I_TipoIns", typeof(string));
    
            var i_OtrosParameter = i_Otros != null ?
                new ObjectParameter("I_Otros", i_Otros) :
                new ObjectParameter("I_Otros", typeof(string));
    
            var i_UsuarioParameter = i_Usuario != null ?
                new ObjectParameter("I_Usuario", i_Usuario) :
                new ObjectParameter("I_Usuario", typeof(string));
    
            var i_FormaParameter = i_Forma != null ?
                new ObjectParameter("I_Forma", i_Forma) :
                new ObjectParameter("I_Forma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRGUR_GuardarFAT_Medicamentos", i_idAtencionParameter, i_CodigoParameter, i_NombreParameter, i_DescripcionPAParameter, i_DOSISParameter, i_ViaParameter, i_DuracionParameter, i_intervaloParameter, i_CantidadParameter, i_TipoInsParameter, i_OtrosParameter, i_UsuarioParameter, i_FormaParameter);
        }
    
        public virtual int PRGUR_guardarSuministroxOIQuirurgica(Nullable<int> i_NroOIQx, string i_TipoIns, string i_Codigo, string i_Observacion, Nullable<int> i_cantidad, string i_Usuario, string i_Equipo)
        {
            var i_NroOIQxParameter = i_NroOIQx.HasValue ?
                new ObjectParameter("I_NroOIQx", i_NroOIQx) :
                new ObjectParameter("I_NroOIQx", typeof(int));
    
            var i_TipoInsParameter = i_TipoIns != null ?
                new ObjectParameter("I_TipoIns", i_TipoIns) :
                new ObjectParameter("I_TipoIns", typeof(string));
    
            var i_CodigoParameter = i_Codigo != null ?
                new ObjectParameter("I_Codigo", i_Codigo) :
                new ObjectParameter("I_Codigo", typeof(string));
    
            var i_ObservacionParameter = i_Observacion != null ?
                new ObjectParameter("I_Observacion", i_Observacion) :
                new ObjectParameter("I_Observacion", typeof(string));
    
            var i_cantidadParameter = i_cantidad.HasValue ?
                new ObjectParameter("I_cantidad", i_cantidad) :
                new ObjectParameter("I_cantidad", typeof(int));
    
            var i_UsuarioParameter = i_Usuario != null ?
                new ObjectParameter("I_Usuario", i_Usuario) :
                new ObjectParameter("I_Usuario", typeof(string));
    
            var i_EquipoParameter = i_Equipo != null ?
                new ObjectParameter("I_Equipo", i_Equipo) :
                new ObjectParameter("I_Equipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRGUR_guardarSuministroxOIQuirurgica", i_NroOIQxParameter, i_TipoInsParameter, i_CodigoParameter, i_ObservacionParameter, i_cantidadParameter, i_UsuarioParameter, i_EquipoParameter);
        }
    
        public virtual ObjectResult<Listar_GuiasDespacho_Result> PRGUR_Listar_GuiasDespacho(Nullable<int> i_id_NroAtencion)
        {
            var i_id_NroAtencionParameter = i_id_NroAtencion.HasValue ?
                new ObjectParameter("I_id_NroAtencion", i_id_NroAtencion) :
                new ObjectParameter("I_id_NroAtencion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Listar_GuiasDespacho_Result>("PRGUR_Listar_GuiasDespacho", i_id_NroAtencionParameter);
        }
    
        public virtual ObjectResult<ListarCartas_Result> PRGUR_ListarCartas(string i_sBusqueda, string i_CodEspecialidad)
        {
            var i_sBusquedaParameter = i_sBusqueda != null ?
                new ObjectParameter("I_sBusqueda", i_sBusqueda) :
                new ObjectParameter("I_sBusqueda", typeof(string));
    
            var i_CodEspecialidadParameter = i_CodEspecialidad != null ?
                new ObjectParameter("I_CodEspecialidad", i_CodEspecialidad) :
                new ObjectParameter("I_CodEspecialidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCartas_Result>("PRGUR_ListarCartas", i_sBusquedaParameter, i_CodEspecialidadParameter);
        }
    
        public virtual ObjectResult<ListarCartasAuditor_Result> PRGUR_ListarCartasAuditor(string i_sBusqueda, string i_FInic, string i_FFin, string i_CodEstado, string i_TipoAt)
        {
            var i_sBusquedaParameter = i_sBusqueda != null ?
                new ObjectParameter("I_sBusqueda", i_sBusqueda) :
                new ObjectParameter("I_sBusqueda", typeof(string));
    
            var i_FInicParameter = i_FInic != null ?
                new ObjectParameter("I_FInic", i_FInic) :
                new ObjectParameter("I_FInic", typeof(string));
    
            var i_FFinParameter = i_FFin != null ?
                new ObjectParameter("I_FFin", i_FFin) :
                new ObjectParameter("I_FFin", typeof(string));
    
            var i_CodEstadoParameter = i_CodEstado != null ?
                new ObjectParameter("I_CodEstado", i_CodEstado) :
                new ObjectParameter("I_CodEstado", typeof(string));
    
            var i_TipoAtParameter = i_TipoAt != null ?
                new ObjectParameter("I_TipoAt", i_TipoAt) :
                new ObjectParameter("I_TipoAt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCartasAuditor_Result>("PRGUR_ListarCartasAuditor", i_sBusquedaParameter, i_FInicParameter, i_FFinParameter, i_CodEstadoParameter, i_TipoAtParameter);
        }
    
        public virtual ObjectResult<ListarCartasOIQx_Result> PRGUR_ListarCartasOIQx(string i_sBusqueda, string i_FInic, string i_FFin, string i_CodEspecialidad, string i_CodEstadoPreQx, string i_CodTipoCirugia, Nullable<bool> i_ReqPreQx)
        {
            var i_sBusquedaParameter = i_sBusqueda != null ?
                new ObjectParameter("I_sBusqueda", i_sBusqueda) :
                new ObjectParameter("I_sBusqueda", typeof(string));
    
            var i_FInicParameter = i_FInic != null ?
                new ObjectParameter("I_FInic", i_FInic) :
                new ObjectParameter("I_FInic", typeof(string));
    
            var i_FFinParameter = i_FFin != null ?
                new ObjectParameter("I_FFin", i_FFin) :
                new ObjectParameter("I_FFin", typeof(string));
    
            var i_CodEspecialidadParameter = i_CodEspecialidad != null ?
                new ObjectParameter("I_CodEspecialidad", i_CodEspecialidad) :
                new ObjectParameter("I_CodEspecialidad", typeof(string));
    
            var i_CodEstadoPreQxParameter = i_CodEstadoPreQx != null ?
                new ObjectParameter("I_CodEstadoPreQx", i_CodEstadoPreQx) :
                new ObjectParameter("I_CodEstadoPreQx", typeof(string));
    
            var i_CodTipoCirugiaParameter = i_CodTipoCirugia != null ?
                new ObjectParameter("I_CodTipoCirugia", i_CodTipoCirugia) :
                new ObjectParameter("I_CodTipoCirugia", typeof(string));
    
            var i_ReqPreQxParameter = i_ReqPreQx.HasValue ?
                new ObjectParameter("I_ReqPreQx", i_ReqPreQx) :
                new ObjectParameter("I_ReqPreQx", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCartasOIQx_Result>("PRGUR_ListarCartasOIQx", i_sBusquedaParameter, i_FInicParameter, i_FFinParameter, i_CodEspecialidadParameter, i_CodEstadoPreQxParameter, i_CodTipoCirugiaParameter, i_ReqPreQxParameter);
        }
    
        public virtual ObjectResult<ListarCartasOIQxProgramador_Result> PRGUR_ListarCartasOIQxProgramador(string i_FInic, string i_FFin, string i_CodEstadoCarta, string i_CodEstadoPreQx, Nullable<bool> i_QxProgramado)
        {
            var i_FInicParameter = i_FInic != null ?
                new ObjectParameter("I_FInic", i_FInic) :
                new ObjectParameter("I_FInic", typeof(string));
    
            var i_FFinParameter = i_FFin != null ?
                new ObjectParameter("I_FFin", i_FFin) :
                new ObjectParameter("I_FFin", typeof(string));
    
            var i_CodEstadoCartaParameter = i_CodEstadoCarta != null ?
                new ObjectParameter("I_CodEstadoCarta", i_CodEstadoCarta) :
                new ObjectParameter("I_CodEstadoCarta", typeof(string));
    
            var i_CodEstadoPreQxParameter = i_CodEstadoPreQx != null ?
                new ObjectParameter("I_CodEstadoPreQx", i_CodEstadoPreQx) :
                new ObjectParameter("I_CodEstadoPreQx", typeof(string));
    
            var i_QxProgramadoParameter = i_QxProgramado.HasValue ?
                new ObjectParameter("I_QxProgramado", i_QxProgramado) :
                new ObjectParameter("I_QxProgramado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCartasOIQxProgramador_Result>("PRGUR_ListarCartasOIQxProgramador", i_FInicParameter, i_FFinParameter, i_CodEstadoCartaParameter, i_CodEstadoPreQxParameter, i_QxProgramadoParameter);
        }
    
        public virtual ObjectResult<ListarCartasServicios_Result> PRGUR_ListarCartasServicios(string i_sBusqueda, string i_FInic, string i_FFin, string i_CodEstado, string i_TipoAt)
        {
            var i_sBusquedaParameter = i_sBusqueda != null ?
                new ObjectParameter("I_sBusqueda", i_sBusqueda) :
                new ObjectParameter("I_sBusqueda", typeof(string));
    
            var i_FInicParameter = i_FInic != null ?
                new ObjectParameter("I_FInic", i_FInic) :
                new ObjectParameter("I_FInic", typeof(string));
    
            var i_FFinParameter = i_FFin != null ?
                new ObjectParameter("I_FFin", i_FFin) :
                new ObjectParameter("I_FFin", typeof(string));
    
            var i_CodEstadoParameter = i_CodEstado != null ?
                new ObjectParameter("I_CodEstado", i_CodEstado) :
                new ObjectParameter("I_CodEstado", typeof(string));
    
            var i_TipoAtParameter = i_TipoAt != null ?
                new ObjectParameter("I_TipoAt", i_TipoAt) :
                new ObjectParameter("I_TipoAt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCartasServicios_Result>("PRGUR_ListarCartasServicios", i_sBusquedaParameter, i_FInicParameter, i_FFinParameter, i_CodEstadoParameter, i_TipoAtParameter);
        }
    
        public virtual ObjectResult<string> PRGUR_ListarEstadosFarmacia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PRGUR_ListarEstadosFarmacia");
        }
    
        public virtual ObjectResult<ListarFAT_Result> PRGUR_ListarFAT(string i_FInic, string i_FFin, string i_user)
        {
            var i_FInicParameter = i_FInic != null ?
                new ObjectParameter("I_FInic", i_FInic) :
                new ObjectParameter("I_FInic", typeof(string));
    
            var i_FFinParameter = i_FFin != null ?
                new ObjectParameter("I_FFin", i_FFin) :
                new ObjectParameter("I_FFin", typeof(string));
    
            var i_userParameter = i_user != null ?
                new ObjectParameter("I_user", i_user) :
                new ObjectParameter("I_user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarFAT_Result>("PRGUR_ListarFAT", i_FInicParameter, i_FFinParameter, i_userParameter);
        }
    
        public virtual ObjectResult<ListarFAT_Farmacia_Result> PRGUR_ListarFAT_Farmacia(string i_FInic, string i_FFin, string i_Busqueda, string i_CodEspecialidad, string i_Estado)
        {
            var i_FInicParameter = i_FInic != null ?
                new ObjectParameter("I_FInic", i_FInic) :
                new ObjectParameter("I_FInic", typeof(string));
    
            var i_FFinParameter = i_FFin != null ?
                new ObjectParameter("I_FFin", i_FFin) :
                new ObjectParameter("I_FFin", typeof(string));
    
            var i_BusquedaParameter = i_Busqueda != null ?
                new ObjectParameter("I_Busqueda", i_Busqueda) :
                new ObjectParameter("I_Busqueda", typeof(string));
    
            var i_CodEspecialidadParameter = i_CodEspecialidad != null ?
                new ObjectParameter("I_CodEspecialidad", i_CodEspecialidad) :
                new ObjectParameter("I_CodEspecialidad", typeof(string));
    
            var i_EstadoParameter = i_Estado != null ?
                new ObjectParameter("I_Estado", i_Estado) :
                new ObjectParameter("I_Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarFAT_Farmacia_Result>("PRGUR_ListarFAT_Farmacia", i_FInicParameter, i_FFinParameter, i_BusquedaParameter, i_CodEspecialidadParameter, i_EstadoParameter);
        }
    
        public virtual ObjectResult<ListarOIQx_Result> PRGUR_ListarOIQx(string i_sBusqueda, string i_FInic, string i_FFin, string i_CodEstado, string i_CodEspecialidad, Nullable<bool> i_CConfirmada, string i_CMP)
        {
            var i_sBusquedaParameter = i_sBusqueda != null ?
                new ObjectParameter("I_sBusqueda", i_sBusqueda) :
                new ObjectParameter("I_sBusqueda", typeof(string));
    
            var i_FInicParameter = i_FInic != null ?
                new ObjectParameter("I_FInic", i_FInic) :
                new ObjectParameter("I_FInic", typeof(string));
    
            var i_FFinParameter = i_FFin != null ?
                new ObjectParameter("I_FFin", i_FFin) :
                new ObjectParameter("I_FFin", typeof(string));
    
            var i_CodEstadoParameter = i_CodEstado != null ?
                new ObjectParameter("I_CodEstado", i_CodEstado) :
                new ObjectParameter("I_CodEstado", typeof(string));
    
            var i_CodEspecialidadParameter = i_CodEspecialidad != null ?
                new ObjectParameter("I_CodEspecialidad", i_CodEspecialidad) :
                new ObjectParameter("I_CodEspecialidad", typeof(string));
    
            var i_CConfirmadaParameter = i_CConfirmada.HasValue ?
                new ObjectParameter("I_CConfirmada", i_CConfirmada) :
                new ObjectParameter("I_CConfirmada", typeof(bool));
    
            var i_CMPParameter = i_CMP != null ?
                new ObjectParameter("I_CMP", i_CMP) :
                new ObjectParameter("I_CMP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarOIQx_Result>("PRGUR_ListarOIQx", i_sBusquedaParameter, i_FInicParameter, i_FFinParameter, i_CodEstadoParameter, i_CodEspecialidadParameter, i_CConfirmadaParameter, i_CMPParameter);
        }
    
        public virtual int PRGUR_LOG_DEBUG(string i_usuario, string i_tipo, string i_sp, string i_data, string i_Ref, string i_MSJ)
        {
            var i_usuarioParameter = i_usuario != null ?
                new ObjectParameter("I_usuario", i_usuario) :
                new ObjectParameter("I_usuario", typeof(string));
    
            var i_tipoParameter = i_tipo != null ?
                new ObjectParameter("I_tipo", i_tipo) :
                new ObjectParameter("I_tipo", typeof(string));
    
            var i_spParameter = i_sp != null ?
                new ObjectParameter("I_sp", i_sp) :
                new ObjectParameter("I_sp", typeof(string));
    
            var i_dataParameter = i_data != null ?
                new ObjectParameter("I_data", i_data) :
                new ObjectParameter("I_data", typeof(string));
    
            var i_RefParameter = i_Ref != null ?
                new ObjectParameter("I_Ref", i_Ref) :
                new ObjectParameter("I_Ref", typeof(string));
    
            var i_MSJParameter = i_MSJ != null ?
                new ObjectParameter("I_MSJ", i_MSJ) :
                new ObjectParameter("I_MSJ", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRGUR_LOG_DEBUG", i_usuarioParameter, i_tipoParameter, i_spParameter, i_dataParameter, i_RefParameter, i_MSJParameter);
        }
    
        public virtual int PRGUR_UPD_AUDITORIA_CARTA(string i_Importe, string i_Diagnostico, Nullable<int> i_CodSolicitud, string i_NroSolicitud, string i_Usuario, string i_Equipo, string i_estadoAuditar, string i_motivoEstado, string i_observacionMedica, string i_observacionInterna, byte[] i_archivoCarta, string i_NombreArchivo, string i_departamento)
        {
            var i_ImporteParameter = i_Importe != null ?
                new ObjectParameter("I_Importe", i_Importe) :
                new ObjectParameter("I_Importe", typeof(string));
    
            var i_DiagnosticoParameter = i_Diagnostico != null ?
                new ObjectParameter("I_Diagnostico", i_Diagnostico) :
                new ObjectParameter("I_Diagnostico", typeof(string));
    
            var i_CodSolicitudParameter = i_CodSolicitud.HasValue ?
                new ObjectParameter("I_CodSolicitud", i_CodSolicitud) :
                new ObjectParameter("I_CodSolicitud", typeof(int));
    
            var i_NroSolicitudParameter = i_NroSolicitud != null ?
                new ObjectParameter("I_NroSolicitud", i_NroSolicitud) :
                new ObjectParameter("I_NroSolicitud", typeof(string));
    
            var i_UsuarioParameter = i_Usuario != null ?
                new ObjectParameter("I_Usuario", i_Usuario) :
                new ObjectParameter("I_Usuario", typeof(string));
    
            var i_EquipoParameter = i_Equipo != null ?
                new ObjectParameter("I_Equipo", i_Equipo) :
                new ObjectParameter("I_Equipo", typeof(string));
    
            var i_estadoAuditarParameter = i_estadoAuditar != null ?
                new ObjectParameter("I_estadoAuditar", i_estadoAuditar) :
                new ObjectParameter("I_estadoAuditar", typeof(string));
    
            var i_motivoEstadoParameter = i_motivoEstado != null ?
                new ObjectParameter("I_motivoEstado", i_motivoEstado) :
                new ObjectParameter("I_motivoEstado", typeof(string));
    
            var i_observacionMedicaParameter = i_observacionMedica != null ?
                new ObjectParameter("I_observacionMedica", i_observacionMedica) :
                new ObjectParameter("I_observacionMedica", typeof(string));
    
            var i_observacionInternaParameter = i_observacionInterna != null ?
                new ObjectParameter("I_observacionInterna", i_observacionInterna) :
                new ObjectParameter("I_observacionInterna", typeof(string));
    
            var i_archivoCartaParameter = i_archivoCarta != null ?
                new ObjectParameter("I_archivoCarta", i_archivoCarta) :
                new ObjectParameter("I_archivoCarta", typeof(byte[]));
    
            var i_NombreArchivoParameter = i_NombreArchivo != null ?
                new ObjectParameter("I_NombreArchivo", i_NombreArchivo) :
                new ObjectParameter("I_NombreArchivo", typeof(string));
    
            var i_departamentoParameter = i_departamento != null ?
                new ObjectParameter("I_departamento", i_departamento) :
                new ObjectParameter("I_departamento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRGUR_UPD_AUDITORIA_CARTA", i_ImporteParameter, i_DiagnosticoParameter, i_CodSolicitudParameter, i_NroSolicitudParameter, i_UsuarioParameter, i_EquipoParameter, i_estadoAuditarParameter, i_motivoEstadoParameter, i_observacionMedicaParameter, i_observacionInternaParameter, i_archivoCartaParameter, i_NombreArchivoParameter, i_departamentoParameter);
        }
    
        public virtual ObjectResult<PacienteFAT_Result> PRFAT_BUSCAR_HC_DOC(string iS_HC_DOCUMENTO, string iS_tipoBusqueda)
        {
            var iS_HC_DOCUMENTOParameter = iS_HC_DOCUMENTO != null ?
                new ObjectParameter("IS_HC_DOCUMENTO", iS_HC_DOCUMENTO) :
                new ObjectParameter("IS_HC_DOCUMENTO", typeof(string));
    
            var iS_tipoBusquedaParameter = iS_tipoBusqueda != null ?
                new ObjectParameter("IS_tipoBusqueda", iS_tipoBusqueda) :
                new ObjectParameter("IS_tipoBusqueda", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PacienteFAT_Result>("PRFAT_BUSCAR_HC_DOC", iS_HC_DOCUMENTOParameter, iS_tipoBusquedaParameter);
        }
    
        public virtual int PRGUR_ELIMINA_VIDEOCONFERENCIA(Nullable<int> id_videoconferencia, string is_usr_eliminacion)
        {
            var id_videoconferenciaParameter = id_videoconferencia.HasValue ?
                new ObjectParameter("id_videoconferencia", id_videoconferencia) :
                new ObjectParameter("id_videoconferencia", typeof(int));
    
            var is_usr_eliminacionParameter = is_usr_eliminacion != null ?
                new ObjectParameter("is_usr_eliminacion", is_usr_eliminacion) :
                new ObjectParameter("is_usr_eliminacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRGUR_ELIMINA_VIDEOCONFERENCIA", id_videoconferenciaParameter, is_usr_eliminacionParameter);
        }
    
        public virtual ObjectResult<PRGUR_GetFAT_VIDEOCONFERENCIA_Result> PRGUR_GetFAT_VIDEOCONFERENCIA(Nullable<int> id_atencion)
        {
            var id_atencionParameter = id_atencion.HasValue ?
                new ObjectParameter("id_atencion", id_atencion) :
                new ObjectParameter("id_atencion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRGUR_GetFAT_VIDEOCONFERENCIA_Result>("PRGUR_GetFAT_VIDEOCONFERENCIA", id_atencionParameter);
        }
    
        public virtual ObjectResult<PRGUR_GetFAT_VIDEOCONFERENCIA_GUID_Result> PRGUR_GetFAT_VIDEOCONFERENCIA_GUID(Nullable<System.Guid> ui_guid)
        {
            var ui_guidParameter = ui_guid.HasValue ?
                new ObjectParameter("ui_guid", ui_guid) :
                new ObjectParameter("ui_guid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRGUR_GetFAT_VIDEOCONFERENCIA_GUID_Result>("PRGUR_GetFAT_VIDEOCONFERENCIA_GUID", ui_guidParameter);
        }
    
        public virtual int PRGUR_GUARDA_VIDEOCONFERENCIA(Nullable<int> id_atencion, Nullable<System.Guid> ig_guid, string is_video_token, string is_url_video, Nullable<System.DateTime> id_fec_registro, Nullable<int> is_estado, Nullable<System.DateTime> id_fec_creacion, string is_usr_creacion)
        {
            var id_atencionParameter = id_atencion.HasValue ?
                new ObjectParameter("id_atencion", id_atencion) :
                new ObjectParameter("id_atencion", typeof(int));
    
            var ig_guidParameter = ig_guid.HasValue ?
                new ObjectParameter("ig_guid", ig_guid) :
                new ObjectParameter("ig_guid", typeof(System.Guid));
    
            var is_video_tokenParameter = is_video_token != null ?
                new ObjectParameter("is_video_token", is_video_token) :
                new ObjectParameter("is_video_token", typeof(string));
    
            var is_url_videoParameter = is_url_video != null ?
                new ObjectParameter("is_url_video", is_url_video) :
                new ObjectParameter("is_url_video", typeof(string));
    
            var id_fec_registroParameter = id_fec_registro.HasValue ?
                new ObjectParameter("Id_fec_registro", id_fec_registro) :
                new ObjectParameter("Id_fec_registro", typeof(System.DateTime));
    
            var is_estadoParameter = is_estado.HasValue ?
                new ObjectParameter("is_estado", is_estado) :
                new ObjectParameter("is_estado", typeof(int));
    
            var id_fec_creacionParameter = id_fec_creacion.HasValue ?
                new ObjectParameter("Id_fec_creacion", id_fec_creacion) :
                new ObjectParameter("Id_fec_creacion", typeof(System.DateTime));
    
            var is_usr_creacionParameter = is_usr_creacion != null ?
                new ObjectParameter("is_usr_creacion", is_usr_creacion) :
                new ObjectParameter("is_usr_creacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRGUR_GUARDA_VIDEOCONFERENCIA", id_atencionParameter, ig_guidParameter, is_video_tokenParameter, is_url_videoParameter, id_fec_registroParameter, is_estadoParameter, id_fec_creacionParameter, is_usr_creacionParameter);
        }
    
        public virtual ObjectResult<getRNE_Result> PRGUR_Buscar_RNE(string i_sBusCMP)
        {
            var i_sBusCMPParameter = i_sBusCMP != null ?
                new ObjectParameter("I_sBusCMP", i_sBusCMP) :
                new ObjectParameter("I_sBusCMP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRNE_Result>("PRGUR_Buscar_RNE", i_sBusCMPParameter);
        }
    
        public virtual ObjectResult<ServiciosFAT_Result> PRGUR_ListarFAT_Servicios(string i_FInic, string i_FFin, string i_Busqueda, string i_CodEspecialidad, string i_CodTIPO)
        {
            var i_FInicParameter = i_FInic != null ?
                new ObjectParameter("I_FInic", i_FInic) :
                new ObjectParameter("I_FInic", typeof(string));
    
            var i_FFinParameter = i_FFin != null ?
                new ObjectParameter("I_FFin", i_FFin) :
                new ObjectParameter("I_FFin", typeof(string));
    
            var i_BusquedaParameter = i_Busqueda != null ?
                new ObjectParameter("I_Busqueda", i_Busqueda) :
                new ObjectParameter("I_Busqueda", typeof(string));
    
            var i_CodEspecialidadParameter = i_CodEspecialidad != null ?
                new ObjectParameter("I_CodEspecialidad", i_CodEspecialidad) :
                new ObjectParameter("I_CodEspecialidad", typeof(string));
    
            var i_CodTIPOParameter = i_CodTIPO != null ?
                new ObjectParameter("I_CodTIPO", i_CodTIPO) :
                new ObjectParameter("I_CodTIPO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ServiciosFAT_Result>("PRGUR_ListarFAT_Servicios", i_FInicParameter, i_FFinParameter, i_BusquedaParameter, i_CodEspecialidadParameter, i_CodTIPOParameter);
        }
    
        public virtual int PRGUR_GUARDA_VIDEOCONFBITACORA(Nullable<int> id_video_conferencia, string is_evento, Nullable<System.DateTime> id_fec_creacion, string is_usr_creacion)
        {
            var id_video_conferenciaParameter = id_video_conferencia.HasValue ?
                new ObjectParameter("id_video_conferencia", id_video_conferencia) :
                new ObjectParameter("id_video_conferencia", typeof(int));
    
            var is_eventoParameter = is_evento != null ?
                new ObjectParameter("is_evento", is_evento) :
                new ObjectParameter("is_evento", typeof(string));
    
            var id_fec_creacionParameter = id_fec_creacion.HasValue ?
                new ObjectParameter("Id_fec_creacion", id_fec_creacion) :
                new ObjectParameter("Id_fec_creacion", typeof(System.DateTime));
    
            var is_usr_creacionParameter = is_usr_creacion != null ?
                new ObjectParameter("is_usr_creacion", is_usr_creacion) :
                new ObjectParameter("is_usr_creacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRGUR_GUARDA_VIDEOCONFBITACORA", id_video_conferenciaParameter, is_eventoParameter, id_fec_creacionParameter, is_usr_creacionParameter);
        }
    
        public virtual ObjectResult<ListarFAT_GS_Result> PRGUR_ListarFAT_GS(string i_FInic, string i_FFin, string i_Busqueda, string i_CodEspecialidad, Nullable<int> i_CodEstado, string i_Medico)
        {
            var i_FInicParameter = i_FInic != null ?
                new ObjectParameter("I_FInic", i_FInic) :
                new ObjectParameter("I_FInic", typeof(string));
    
            var i_FFinParameter = i_FFin != null ?
                new ObjectParameter("I_FFin", i_FFin) :
                new ObjectParameter("I_FFin", typeof(string));
    
            var i_BusquedaParameter = i_Busqueda != null ?
                new ObjectParameter("I_Busqueda", i_Busqueda) :
                new ObjectParameter("I_Busqueda", typeof(string));
    
            var i_CodEspecialidadParameter = i_CodEspecialidad != null ?
                new ObjectParameter("I_CodEspecialidad", i_CodEspecialidad) :
                new ObjectParameter("I_CodEspecialidad", typeof(string));
    
            var i_CodEstadoParameter = i_CodEstado.HasValue ?
                new ObjectParameter("I_CodEstado", i_CodEstado) :
                new ObjectParameter("I_CodEstado", typeof(int));
    
            var i_MedicoParameter = i_Medico != null ?
                new ObjectParameter("I_Medico", i_Medico) :
                new ObjectParameter("I_Medico", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarFAT_GS_Result>("PRGUR_ListarFAT_GS", i_FInicParameter, i_FFinParameter, i_BusquedaParameter, i_CodEspecialidadParameter, i_CodEstadoParameter, i_MedicoParameter);
        }
    
        public virtual ObjectResult<FAT_Reporte_Result> PRGUR_getFAT_Reporte(Nullable<int> i_idFAT)
        {
            var i_idFATParameter = i_idFAT.HasValue ?
                new ObjectParameter("I_idFAT", i_idFAT) :
                new ObjectParameter("I_idFAT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FAT_Reporte_Result>("PRGUR_getFAT_Reporte", i_idFATParameter);
        }
    
        public virtual ObjectResult<FAT_Result> PRGUR_GetFAT(Nullable<int> i_idFAT)
        {
            var i_idFATParameter = i_idFAT.HasValue ?
                new ObjectParameter("I_idFAT", i_idFAT) :
                new ObjectParameter("I_idFAT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FAT_Result>("PRGUR_GetFAT", i_idFATParameter);
        }
    }
}
