//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_CapaAccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FAT_CRPEntities : DbContext
    {
        public FAT_CRPEntities()
            : base("name=FAT_CRPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TFAT_PERMISOS> TFAT_PERMISOS { get; set; }
        public virtual DbSet<TMAE_CIE> TMAE_CIE { get; set; }
        public virtual DbSet<TMAE_MEDICOS> TMAE_MEDICOS { get; set; }
        public virtual DbSet<TMAE_PACIENTE> TMAE_PACIENTE { get; set; }
        public virtual DbSet<TMAE_PROCEDIMIENTOS> TMAE_PROCEDIMIENTOS { get; set; }
        public virtual DbSet<TFAT_DIAGNOSTICO> TFAT_DIAGNOSTICO { get; set; }
        public virtual DbSet<TFAT_LABORATORIO> TFAT_LABORATORIO { get; set; }
        public virtual DbSet<TFAT_RADIOLOGiA> TFAT_RADIOLOGiA { get; set; }
        public virtual DbSet<TMAE_FINANCIADOR> TMAE_FINANCIADOR { get; set; }
        public virtual DbSet<TFAT_USUARIO> TFAT_USUARIO { get; set; }
        public virtual DbSet<TFAT_ATENCION> TFAT_ATENCION { get; set; }
    
        public virtual ObjectResult<PRFAT_ListarTeleconsulta_Result> PRFAT_ListarTeleconsulta(string i_FInic, string i_FFin, string i_user)
        {
            var i_FInicParameter = i_FInic != null ?
                new ObjectParameter("I_FInic", i_FInic) :
                new ObjectParameter("I_FInic", typeof(string));
    
            var i_FFinParameter = i_FFin != null ?
                new ObjectParameter("I_FFin", i_FFin) :
                new ObjectParameter("I_FFin", typeof(string));
    
            var i_userParameter = i_user != null ?
                new ObjectParameter("I_user", i_user) :
                new ObjectParameter("I_user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRFAT_ListarTeleconsulta_Result>("PRFAT_ListarTeleconsulta", i_FInicParameter, i_FFinParameter, i_userParameter);
        }
    
        public virtual ObjectResult<PRFAT_Autocompletar_Result> PRFAT_Autocompletar(string i_STipo, string i_term)
        {
            var i_STipoParameter = i_STipo != null ?
                new ObjectParameter("I_STipo", i_STipo) :
                new ObjectParameter("I_STipo", typeof(string));
    
            var i_termParameter = i_term != null ?
                new ObjectParameter("I_term", i_term) :
                new ObjectParameter("I_term", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRFAT_Autocompletar_Result>("PRFAT_Autocompletar", i_STipoParameter, i_termParameter);
        }
    }
}
