//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_CapaAccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class operacionesEntities : DbContext
    {
        public operacionesEntities()
            : base("name=operacionesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<T_EPI_DIAGNOSTICO> PRGUR_DIAGNOSTICOSxINF(Nullable<int> i_nCodInforme)
        {
            var i_nCodInformeParameter = i_nCodInforme.HasValue ?
                new ObjectParameter("I_nCodInforme", i_nCodInforme) :
                new ObjectParameter("I_nCodInforme", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<T_EPI_DIAGNOSTICO>("PRGUR_DIAGNOSTICOSxINF", i_nCodInformeParameter);
        }
    
        public virtual ObjectResult<PRGUR_INFORMEPICR_Result> PRGUR_INFORMEPICR(string i_sHC, string i_dFechaIngreso)
        {
            var i_sHCParameter = i_sHC != null ?
                new ObjectParameter("I_sHC", i_sHC) :
                new ObjectParameter("I_sHC", typeof(string));
    
            var i_dFechaIngresoParameter = i_dFechaIngreso != null ?
                new ObjectParameter("I_dFechaIngreso", i_dFechaIngreso) :
                new ObjectParameter("I_dFechaIngreso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRGUR_INFORMEPICR_Result>("PRGUR_INFORMEPICR", i_sHCParameter, i_dFechaIngresoParameter);
        }
    }
}
