//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_CapaAccesoDatos
{
    using System;
    
    public partial class T_EPI_DIAGNOSTICO
    {
        public string C_DIAG_COD_DIAGSELEC { get; set; }
        public string C_DIAG_DESCRIPCION { get; set; }
        public string C_DIAG_TIPO_DIAG { get; set; }
    }
}
