//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFAT_PERMISOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TFAT_PERMISOS()
        {
            this.TFAT_USUARIO = new HashSet<TFAT_USUARIO>();
        }
    
        public Nullable<bool> FPER_READ { get; set; }
        public Nullable<bool> FPER_WRITE { get; set; }
        public int CPER_PERMISO { get; set; }
        public string SPER_MENU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TFAT_USUARIO> TFAT_USUARIO { get; set; }
    }
}
