//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFAT_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TFAT_USUARIO()
        {
            this.TMAE_MEDICOS = new HashSet<TMAE_MEDICOS>();
        }
    
        public int CUSU_IDUSUARIO { get; set; }
        public string SUSU_CODUSUARIO { get; set; }
        public string SUSU_PASSWORD { get; set; }
        public int CUSU_PERMISO { get; set; }
        public bool SUSU_ESTADO { get; set; }
    
        public virtual TFAT_PERMISOS TFAT_PERMISOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMAE_MEDICOS> TMAE_MEDICOS { get; set; }
    }
}
