//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFAT_ATENCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TFAT_ATENCION()
        {
            this.TFAT_DIAGNOSTICO = new HashSet<TFAT_DIAGNOSTICO>();
        }
    
        public int CFAT_ID_ATENCION { get; set; }
        public Nullable<int> CFAT_ID_TIPOATENCION { get; set; }
        public string SFAT_ANAMNESIS { get; set; }
        public string SFAT_MOTIVO { get; set; }
        public string SFAT_TRATAMIENTO { get; set; }
        public Nullable<int> CFAT_ESTADO { get; set; }
        public string SFAT_USR_CREACION { get; set; }
        public Nullable<System.DateTime> DFAT_FEC_CREACION { get; set; }
        public string SFAT_OAA { get; set; }
        public Nullable<System.DateTime> DFAT_FECHA_OAA { get; set; }
        public string SFAT_USUARIO_OAA { get; set; }
        public Nullable<bool> BFAT_ESTADOREGISTRO { get; set; }
        public Nullable<System.DateTime> DFAT_FECHA_CITA { get; set; }
        public string SFAT_HORA_CITA { get; set; }
        public string SFAT_MEDIOCONTACTO { get; set; }
        public int CFAT_ID_MEDICO { get; set; }
        public int CPAC_ID_PACIENTE { get; set; }
    
        public virtual TMAE_MEDICOS TMAE_MEDICOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TFAT_DIAGNOSTICO> TFAT_DIAGNOSTICO { get; set; }
        public virtual TFAT_LABORATORIO TFAT_LABORATORIO { get; set; }
        public virtual TFAT_RADIOLOGiA TFAT_RADIOLOGiA { get; set; }
        public virtual TMAE_PACIENTE TMAE_PACIENTE { get; set; }
    }
}
