//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGUR_LOGDEBUG
    {
        public int CGUR_PK { get; set; }
        public string SGUR_RUTA { get; set; }
        public string SGUR_TIPO { get; set; }
        public string SGUR_PARAMETROS { get; set; }
        public string SGUR_MENSAJE { get; set; }
        public string SGUR_DETALLE { get; set; }
        public Nullable<System.DateTime> DGUR_FECHACREACION { get; set; }
        public string SGUR_USER { get; set; }
    }
}
