//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMAE_MEDICOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TMAE_MEDICOS()
        {
            this.TFAT_ATENCION = new HashSet<TFAT_ATENCION>();
        }
    
        public int CMED_MAE_MED { get; set; }
        public string SMED_CODMEDICO { get; set; }
        public string SMED_NOMBRESMEDICO { get; set; }
        public string SMED_ESPECIALIDAD { get; set; }
        public string SMED_COD_ESPECIALIDAD { get; set; }
        public string SMED_RNE { get; set; }
        public string SMED_NUMCELULAR { get; set; }
        public string SMED_EMAIL { get; set; }
        public Nullable<int> CMED_USERID { get; set; }
    
        public virtual TFAT_USUARIO TFAT_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TFAT_ATENCION> TFAT_ATENCION { get; set; }
    }
}
