//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMAE_PACIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TMAE_PACIENTE()
        {
            this.TFAT_ATENCION = new HashSet<TFAT_ATENCION>();
        }
    
        public int CPAC_ID_PACIENTE { get; set; }
        public string SPAC_NUM_DOCUMENTO { get; set; }
        public string SPAC_NOMBRES { get; set; }
        public string SPAC_APE_PATERNO { get; set; }
        public string SPAC_APE_MATERNO { get; set; }
        public string SPAC_HC { get; set; }
        public Nullable<int> CPAC_EDAD { get; set; }
        public string SPAC_SEXO { get; set; }
        public string SPAC_EMAIL_PAC { get; set; }
        public string SPAC_CELULAR_PAC { get; set; }
        public string SPAC_TELEFONO_PAC { get; set; }
        public Nullable<int> CPAC_ID_FINANCIADOR { get; set; }
        public Nullable<System.DateTime> DPAC_FEC_ULTIMA_ATENCION { get; set; }
    
        public virtual TMAE_FINANCIADOR TMAE_FINANCIADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TFAT_ATENCION> TFAT_ATENCION { get; set; }
    }
}
