//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2_CapaServiciosGM.PlanSalud_InformacionAfiliado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Afiliado", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Afiliado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.EContrato contratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.EPaciente pacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.EContratante contratanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ETitularContrato titularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ArrayOfBeneficio beneficiosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ArrayOfPregunta declaracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ArrayOfPreexistencia preexistenciasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.EContrato contrato {
            get {
                return this.contratoField;
            }
            set {
                if ((object.ReferenceEquals(this.contratoField, value) != true)) {
                    this.contratoField = value;
                    this.RaisePropertyChanged("contrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.EPaciente paciente {
            get {
                return this.pacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.pacienteField, value) != true)) {
                    this.pacienteField = value;
                    this.RaisePropertyChanged("paciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.EContratante contratante {
            get {
                return this.contratanteField;
            }
            set {
                if ((object.ReferenceEquals(this.contratanteField, value) != true)) {
                    this.contratanteField = value;
                    this.RaisePropertyChanged("contratante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ETitularContrato titular {
            get {
                return this.titularField;
            }
            set {
                if ((object.ReferenceEquals(this.titularField, value) != true)) {
                    this.titularField = value;
                    this.RaisePropertyChanged("titular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ArrayOfBeneficio beneficios {
            get {
                return this.beneficiosField;
            }
            set {
                if ((object.ReferenceEquals(this.beneficiosField, value) != true)) {
                    this.beneficiosField = value;
                    this.RaisePropertyChanged("beneficios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ArrayOfPregunta declaracion {
            get {
                return this.declaracionField;
            }
            set {
                if ((object.ReferenceEquals(this.declaracionField, value) != true)) {
                    this.declaracionField = value;
                    this.RaisePropertyChanged("declaracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ArrayOfPreexistencia preexistencias {
            get {
                return this.preexistenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.preexistenciasField, value) != true)) {
                    this.preexistenciasField = value;
                    this.RaisePropertyChanged("preexistencias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EContrato", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EContrato : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string inicio_vigenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fin_vigenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        private int contratoProcedenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechainscripcionOrigenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string inicio_vigencia {
            get {
                return this.inicio_vigenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.inicio_vigenciaField, value) != true)) {
                    this.inicio_vigenciaField = value;
                    this.RaisePropertyChanged("inicio_vigencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fin_vigencia {
            get {
                return this.fin_vigenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.fin_vigenciaField, value) != true)) {
                    this.fin_vigenciaField = value;
                    this.RaisePropertyChanged("fin_vigencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int contratoProcedencia {
            get {
                return this.contratoProcedenciaField;
            }
            set {
                if ((this.contratoProcedenciaField.Equals(value) != true)) {
                    this.contratoProcedenciaField = value;
                    this.RaisePropertyChanged("contratoProcedencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string fechainscripcionOrigen {
            get {
                return this.fechainscripcionOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.fechainscripcionOrigenField, value) != true)) {
                    this.fechainscripcionOrigenField = value;
                    this.RaisePropertyChanged("fechainscripcionOrigen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EPaciente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EPaciente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numero_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellido_paternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellido_maternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_nacimientoField;
        
        private int edadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string generoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parentescoField;
        
        private int contrato_procedenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_continuidadField;
        
        private int planField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombre_planField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string celularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_afiliadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_afiliacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numero_hcField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tipo_documento {
            get {
                return this.tipo_documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_documentoField, value) != true)) {
                    this.tipo_documentoField = value;
                    this.RaisePropertyChanged("tipo_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numero_documento {
            get {
                return this.numero_documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.numero_documentoField, value) != true)) {
                    this.numero_documentoField = value;
                    this.RaisePropertyChanged("numero_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string segundo_nombre {
            get {
                return this.segundo_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_nombreField, value) != true)) {
                    this.segundo_nombreField = value;
                    this.RaisePropertyChanged("segundo_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string apellido_paterno {
            get {
                return this.apellido_paternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellido_paternoField, value) != true)) {
                    this.apellido_paternoField = value;
                    this.RaisePropertyChanged("apellido_paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string apellido_materno {
            get {
                return this.apellido_maternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellido_maternoField, value) != true)) {
                    this.apellido_maternoField = value;
                    this.RaisePropertyChanged("apellido_materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string fecha_nacimiento {
            get {
                return this.fecha_nacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_nacimientoField, value) != true)) {
                    this.fecha_nacimientoField = value;
                    this.RaisePropertyChanged("fecha_nacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                if ((this.edadField.Equals(value) != true)) {
                    this.edadField = value;
                    this.RaisePropertyChanged("edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string genero {
            get {
                return this.generoField;
            }
            set {
                if ((object.ReferenceEquals(this.generoField, value) != true)) {
                    this.generoField = value;
                    this.RaisePropertyChanged("genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string parentesco {
            get {
                return this.parentescoField;
            }
            set {
                if ((object.ReferenceEquals(this.parentescoField, value) != true)) {
                    this.parentescoField = value;
                    this.RaisePropertyChanged("parentesco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int contrato_procedencia {
            get {
                return this.contrato_procedenciaField;
            }
            set {
                if ((this.contrato_procedenciaField.Equals(value) != true)) {
                    this.contrato_procedenciaField = value;
                    this.RaisePropertyChanged("contrato_procedencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string fecha_continuidad {
            get {
                return this.fecha_continuidadField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_continuidadField, value) != true)) {
                    this.fecha_continuidadField = value;
                    this.RaisePropertyChanged("fecha_continuidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int plan {
            get {
                return this.planField;
            }
            set {
                if ((this.planField.Equals(value) != true)) {
                    this.planField = value;
                    this.RaisePropertyChanged("plan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string nombre_plan {
            get {
                return this.nombre_planField;
            }
            set {
                if ((object.ReferenceEquals(this.nombre_planField, value) != true)) {
                    this.nombre_planField = value;
                    this.RaisePropertyChanged("nombre_plan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string celular {
            get {
                return this.celularField;
            }
            set {
                if ((object.ReferenceEquals(this.celularField, value) != true)) {
                    this.celularField = value;
                    this.RaisePropertyChanged("celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string id_afiliado {
            get {
                return this.id_afiliadoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_afiliadoField, value) != true)) {
                    this.id_afiliadoField = value;
                    this.RaisePropertyChanged("id_afiliado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string fecha_afiliacion {
            get {
                return this.fecha_afiliacionField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_afiliacionField, value) != true)) {
                    this.fecha_afiliacionField = value;
                    this.RaisePropertyChanged("fecha_afiliacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string numero_hc {
            get {
                return this.numero_hcField;
            }
            set {
                if ((object.ReferenceEquals(this.numero_hcField, value) != true)) {
                    this.numero_hcField = value;
                    this.RaisePropertyChanged("numero_hc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EContratante", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EContratante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_personaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numero_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string razon_socialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellido_paternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellido_maternoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tipo_persona {
            get {
                return this.tipo_personaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_personaField, value) != true)) {
                    this.tipo_personaField = value;
                    this.RaisePropertyChanged("tipo_persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipo_documento {
            get {
                return this.tipo_documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_documentoField, value) != true)) {
                    this.tipo_documentoField = value;
                    this.RaisePropertyChanged("tipo_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string numero_documento {
            get {
                return this.numero_documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.numero_documentoField, value) != true)) {
                    this.numero_documentoField = value;
                    this.RaisePropertyChanged("numero_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string razon_social {
            get {
                return this.razon_socialField;
            }
            set {
                if ((object.ReferenceEquals(this.razon_socialField, value) != true)) {
                    this.razon_socialField = value;
                    this.RaisePropertyChanged("razon_social");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string segundo_nombre {
            get {
                return this.segundo_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_nombreField, value) != true)) {
                    this.segundo_nombreField = value;
                    this.RaisePropertyChanged("segundo_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string apellido_paterno {
            get {
                return this.apellido_paternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellido_paternoField, value) != true)) {
                    this.apellido_paternoField = value;
                    this.RaisePropertyChanged("apellido_paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string apellido_materno {
            get {
                return this.apellido_maternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellido_maternoField, value) != true)) {
                    this.apellido_maternoField = value;
                    this.RaisePropertyChanged("apellido_materno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETitularContrato", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ETitularContrato : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numero_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellido_paternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellido_maternoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tipo_documento {
            get {
                return this.tipo_documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_documentoField, value) != true)) {
                    this.tipo_documentoField = value;
                    this.RaisePropertyChanged("tipo_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numero_documento {
            get {
                return this.numero_documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.numero_documentoField, value) != true)) {
                    this.numero_documentoField = value;
                    this.RaisePropertyChanged("numero_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string segundo_nombre {
            get {
                return this.segundo_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_nombreField, value) != true)) {
                    this.segundo_nombreField = value;
                    this.RaisePropertyChanged("segundo_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string apellido_paterno {
            get {
                return this.apellido_paternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellido_paternoField, value) != true)) {
                    this.apellido_paternoField = value;
                    this.RaisePropertyChanged("apellido_paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string apellido_materno {
            get {
                return this.apellido_maternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellido_maternoField, value) != true)) {
                    this.apellido_maternoField = value;
                    this.RaisePropertyChanged("apellido_materno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBeneficio", Namespace="http://tempuri.org/", ItemName="beneficio")]
    [System.SerializableAttribute()]
    public class ArrayOfBeneficio : System.Collections.Generic.List<_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.beneficio> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfPregunta", Namespace="http://tempuri.org/", ItemName="pregunta")]
    [System.SerializableAttribute()]
    public class ArrayOfPregunta : System.Collections.Generic.List<_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.pregunta> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfPreexistencia", Namespace="http://tempuri.org/", ItemName="preexistencia")]
    [System.SerializableAttribute()]
    public class ArrayOfPreexistencia : System.Collections.Generic.List<_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.preexistencia> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="beneficio", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class beneficio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string coberturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string copagoFijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string copagoVariableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cobertura {
            get {
                return this.coberturaField;
            }
            set {
                if ((object.ReferenceEquals(this.coberturaField, value) != true)) {
                    this.coberturaField = value;
                    this.RaisePropertyChanged("cobertura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sede {
            get {
                return this.sedeField;
            }
            set {
                if ((object.ReferenceEquals(this.sedeField, value) != true)) {
                    this.sedeField = value;
                    this.RaisePropertyChanged("sede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string copagoFijo {
            get {
                return this.copagoFijoField;
            }
            set {
                if ((object.ReferenceEquals(this.copagoFijoField, value) != true)) {
                    this.copagoFijoField = value;
                    this.RaisePropertyChanged("copagoFijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string copagoVariable {
            get {
                return this.copagoVariableField;
            }
            set {
                if ((object.ReferenceEquals(this.copagoVariableField, value) != true)) {
                    this.copagoVariableField = value;
                    this.RaisePropertyChanged("copagoVariable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="pregunta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class pregunta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string respuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ArrayOfDolencia dolenciasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string texto {
            get {
                return this.textoField;
            }
            set {
                if ((object.ReferenceEquals(this.textoField, value) != true)) {
                    this.textoField = value;
                    this.RaisePropertyChanged("texto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string respuesta {
            get {
                return this.respuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.respuestaField, value) != true)) {
                    this.respuestaField = value;
                    this.RaisePropertyChanged("respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ArrayOfDolencia dolencias {
            get {
                return this.dolenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.dolenciasField, value) != true)) {
                    this.dolenciasField = value;
                    this.RaisePropertyChanged("dolencias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfDolencia", Namespace="http://tempuri.org/", ItemName="dolencia")]
    [System.SerializableAttribute()]
    public class ArrayOfDolencia : System.Collections.Generic.List<_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.dolencia> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dolencia", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class dolencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string detalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string situacion_actualField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string detalle {
            get {
                return this.detalleField;
            }
            set {
                if ((object.ReferenceEquals(this.detalleField, value) != true)) {
                    this.detalleField = value;
                    this.RaisePropertyChanged("detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string situacion_actual {
            get {
                return this.situacion_actualField;
            }
            set {
                if ((object.ReferenceEquals(this.situacion_actualField, value) != true)) {
                    this.situacion_actualField = value;
                    this.RaisePropertyChanged("situacion_actual");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="preexistencia", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class preexistencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.observacionesField, value) != true)) {
                    this.observacionesField = value;
                    this.RaisePropertyChanged("observaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ECopago", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ECopago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idCopagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desCopagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string copagoFijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string copagoVariableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idCopago {
            get {
                return this.idCopagoField;
            }
            set {
                if ((this.idCopagoField.Equals(value) != true)) {
                    this.idCopagoField = value;
                    this.RaisePropertyChanged("idCopago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string desCopago {
            get {
                return this.desCopagoField;
            }
            set {
                if ((object.ReferenceEquals(this.desCopagoField, value) != true)) {
                    this.desCopagoField = value;
                    this.RaisePropertyChanged("desCopago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string copagoFijo {
            get {
                return this.copagoFijoField;
            }
            set {
                if ((object.ReferenceEquals(this.copagoFijoField, value) != true)) {
                    this.copagoFijoField = value;
                    this.RaisePropertyChanged("copagoFijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string copagoVariable {
            get {
                return this.copagoVariableField;
            }
            set {
                if ((object.ReferenceEquals(this.copagoVariableField, value) != true)) {
                    this.copagoVariableField = value;
                    this.RaisePropertyChanged("copagoVariable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlanSalud_InformacionAfiliado.WSCartadeGarantiaSoap")]
    public interface WSCartadeGarantiaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tipoDocumento del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarAfiliadoPlanSalud", ReplyAction="*")]
        _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludResponse ListarAfiliadoPlanSalud(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarAfiliadoPlanSalud", ReplyAction="*")]
        System.Threading.Tasks.Task<_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludResponse> ListarAfiliadoPlanSaludAsync(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento busquedaAfiliadoPlansalud del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BusquedaAfiliadosPlanSalud", ReplyAction="*")]
        _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludResponse BusquedaAfiliadosPlanSalud(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BusquedaAfiliadosPlanSalud", ReplyAction="*")]
        System.Threading.Tasks.Task<_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludResponse> BusquedaAfiliadosPlanSaludAsync(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento descripcion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarListaCopago", ReplyAction="*")]
        _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoResponse consultarListaCopago(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarListaCopago", ReplyAction="*")]
        System.Threading.Tasks.Task<_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoResponse> consultarListaCopagoAsync(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarAfiliadoPlanSaludRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarAfiliadoPlanSalud", Namespace="http://tempuri.org/", Order=0)]
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludRequestBody Body;
        
        public ListarAfiliadoPlanSaludRequest() {
        }
        
        public ListarAfiliadoPlanSaludRequest(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarAfiliadoPlanSaludRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tipoDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numeroDocumento;
        
        public ListarAfiliadoPlanSaludRequestBody() {
        }
        
        public ListarAfiliadoPlanSaludRequestBody(string tipoDocumento, string numeroDocumento) {
            this.tipoDocumento = tipoDocumento;
            this.numeroDocumento = numeroDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarAfiliadoPlanSaludResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarAfiliadoPlanSaludResponse", Namespace="http://tempuri.org/", Order=0)]
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludResponseBody Body;
        
        public ListarAfiliadoPlanSaludResponse() {
        }
        
        public ListarAfiliadoPlanSaludResponse(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarAfiliadoPlanSaludResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.Afiliado ListarAfiliadoPlanSaludResult;
        
        public ListarAfiliadoPlanSaludResponseBody() {
        }
        
        public ListarAfiliadoPlanSaludResponseBody(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.Afiliado ListarAfiliadoPlanSaludResult) {
            this.ListarAfiliadoPlanSaludResult = ListarAfiliadoPlanSaludResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BusquedaAfiliadosPlanSaludRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BusquedaAfiliadosPlanSalud", Namespace="http://tempuri.org/", Order=0)]
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludRequestBody Body;
        
        public BusquedaAfiliadosPlanSaludRequest() {
        }
        
        public BusquedaAfiliadosPlanSaludRequest(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BusquedaAfiliadosPlanSaludRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string busquedaAfiliadoPlansalud;
        
        public BusquedaAfiliadosPlanSaludRequestBody() {
        }
        
        public BusquedaAfiliadosPlanSaludRequestBody(string busquedaAfiliadoPlansalud) {
            this.busquedaAfiliadoPlansalud = busquedaAfiliadoPlansalud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BusquedaAfiliadosPlanSaludResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BusquedaAfiliadosPlanSaludResponse", Namespace="http://tempuri.org/", Order=0)]
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludResponseBody Body;
        
        public BusquedaAfiliadosPlanSaludResponse() {
        }
        
        public BusquedaAfiliadosPlanSaludResponse(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BusquedaAfiliadosPlanSaludResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.Afiliado[] BusquedaAfiliadosPlanSaludResult;
        
        public BusquedaAfiliadosPlanSaludResponseBody() {
        }
        
        public BusquedaAfiliadosPlanSaludResponseBody(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.Afiliado[] BusquedaAfiliadosPlanSaludResult) {
            this.BusquedaAfiliadosPlanSaludResult = BusquedaAfiliadosPlanSaludResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarListaCopagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarListaCopago", Namespace="http://tempuri.org/", Order=0)]
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoRequestBody Body;
        
        public consultarListaCopagoRequest() {
        }
        
        public consultarListaCopagoRequest(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarListaCopagoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string descripcion;
        
        public consultarListaCopagoRequestBody() {
        }
        
        public consultarListaCopagoRequestBody(string descripcion) {
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarListaCopagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarListaCopagoResponse", Namespace="http://tempuri.org/", Order=0)]
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoResponseBody Body;
        
        public consultarListaCopagoResponse() {
        }
        
        public consultarListaCopagoResponse(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarListaCopagoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ECopago[] consultarListaCopagoResult;
        
        public consultarListaCopagoResponseBody() {
        }
        
        public consultarListaCopagoResponseBody(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ECopago[] consultarListaCopagoResult) {
            this.consultarListaCopagoResult = consultarListaCopagoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSCartadeGarantiaSoapChannel : _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.WSCartadeGarantiaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCartadeGarantiaSoapClient : System.ServiceModel.ClientBase<_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.WSCartadeGarantiaSoap>, _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.WSCartadeGarantiaSoap {
        
        public WSCartadeGarantiaSoapClient() {
        }
        
        public WSCartadeGarantiaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCartadeGarantiaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCartadeGarantiaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCartadeGarantiaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludResponse _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.WSCartadeGarantiaSoap.ListarAfiliadoPlanSalud(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludRequest request) {
            return base.Channel.ListarAfiliadoPlanSalud(request);
        }
        
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.Afiliado ListarAfiliadoPlanSalud(string tipoDocumento, string numeroDocumento) {
            _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludRequest inValue = new _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludRequest();
            inValue.Body = new _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludRequestBody();
            inValue.Body.tipoDocumento = tipoDocumento;
            inValue.Body.numeroDocumento = numeroDocumento;
            _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludResponse retVal = ((_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.WSCartadeGarantiaSoap)(this)).ListarAfiliadoPlanSalud(inValue);
            return retVal.Body.ListarAfiliadoPlanSaludResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludResponse> _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.WSCartadeGarantiaSoap.ListarAfiliadoPlanSaludAsync(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludRequest request) {
            return base.Channel.ListarAfiliadoPlanSaludAsync(request);
        }
        
        public System.Threading.Tasks.Task<_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludResponse> ListarAfiliadoPlanSaludAsync(string tipoDocumento, string numeroDocumento) {
            _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludRequest inValue = new _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludRequest();
            inValue.Body = new _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ListarAfiliadoPlanSaludRequestBody();
            inValue.Body.tipoDocumento = tipoDocumento;
            inValue.Body.numeroDocumento = numeroDocumento;
            return ((_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.WSCartadeGarantiaSoap)(this)).ListarAfiliadoPlanSaludAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludResponse _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.WSCartadeGarantiaSoap.BusquedaAfiliadosPlanSalud(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludRequest request) {
            return base.Channel.BusquedaAfiliadosPlanSalud(request);
        }
        
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.Afiliado[] BusquedaAfiliadosPlanSalud(string busquedaAfiliadoPlansalud) {
            _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludRequest inValue = new _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludRequest();
            inValue.Body = new _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludRequestBody();
            inValue.Body.busquedaAfiliadoPlansalud = busquedaAfiliadoPlansalud;
            _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludResponse retVal = ((_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.WSCartadeGarantiaSoap)(this)).BusquedaAfiliadosPlanSalud(inValue);
            return retVal.Body.BusquedaAfiliadosPlanSaludResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludResponse> _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.WSCartadeGarantiaSoap.BusquedaAfiliadosPlanSaludAsync(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludRequest request) {
            return base.Channel.BusquedaAfiliadosPlanSaludAsync(request);
        }
        
        public System.Threading.Tasks.Task<_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludResponse> BusquedaAfiliadosPlanSaludAsync(string busquedaAfiliadoPlansalud) {
            _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludRequest inValue = new _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludRequest();
            inValue.Body = new _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.BusquedaAfiliadosPlanSaludRequestBody();
            inValue.Body.busquedaAfiliadoPlansalud = busquedaAfiliadoPlansalud;
            return ((_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.WSCartadeGarantiaSoap)(this)).BusquedaAfiliadosPlanSaludAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoResponse _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.WSCartadeGarantiaSoap.consultarListaCopago(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoRequest request) {
            return base.Channel.consultarListaCopago(request);
        }
        
        public _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.ECopago[] consultarListaCopago(string descripcion) {
            _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoRequest inValue = new _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoRequest();
            inValue.Body = new _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoRequestBody();
            inValue.Body.descripcion = descripcion;
            _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoResponse retVal = ((_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.WSCartadeGarantiaSoap)(this)).consultarListaCopago(inValue);
            return retVal.Body.consultarListaCopagoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoResponse> _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.WSCartadeGarantiaSoap.consultarListaCopagoAsync(_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoRequest request) {
            return base.Channel.consultarListaCopagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoResponse> consultarListaCopagoAsync(string descripcion) {
            _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoRequest inValue = new _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoRequest();
            inValue.Body = new _2_CapaServiciosGM.PlanSalud_InformacionAfiliado.consultarListaCopagoRequestBody();
            inValue.Body.descripcion = descripcion;
            return ((_2_CapaServiciosGM.PlanSalud_InformacionAfiliado.WSCartadeGarantiaSoap)(this)).consultarListaCopagoAsync(inValue);
        }
    }
}
